// AUTO-GENERATED by scripts/bundle-audit-export-pubkey.mjs at 2026-08-15T00:15:01.275Z.
// Source pem: packages/core/security/audit-export-pubkey.pem
// RAW-bytes sha256: 224ee86985c69cee4f616104da1819eeab13c1c640147b4ca55d874326c7b7cd
// DO NOT EDIT — regenerate via `node scripts/bundle-audit-export-pubkey.mjs` or
// the prepublishOnly hook (which runs on every npm publish).

/**
 * Ed25519 public key for verifying the signed /audit-export envelope from
 * massu.ai. Used by
 * packages/core/src/security/governance-export-verifier.ts to reject forged /
 * tampered governance audit exports.
 *
 * A signed audit export is a compliance/authenticity artifact, so the verifier
 * has NO transition mode: an unsigned or invalid-signature envelope is REJECTED.
 *
 * PA2-002 (plan-2026-06-01-enterprise-governance-audit-export).
 *
 * To rotate: regenerate the keypair via scripts/generate-audit-export-keypair.mjs,
 * append the new RAW-bytes sha256 to KNOWN_PUBKEY_FINGERPRINTS in
 * scripts/bundle-audit-export-pubkey.mjs (DO NOT delete the old entry during the
 * rotation grace window), then run `node scripts/bundle-audit-export-pubkey.mjs`.
 * Operator then updates the Supabase Edge Function secret
 * `AUDIT_EXPORT_SIGNING_PRIVATE_KEY_B64` with the new private key.
 */
export const AUDIT_EXPORT_PUBKEY_ED25519: Uint8Array = new Uint8Array([132, 99, 7, 134, 101, 194, 127, 202, 90, 99, 201, 199, 185, 160, 95, 47, 90, 75, 19, 49, 95, 7, 92, 154, 211, 196, 134, 82, 230, 147, 178, 10]);

/** Hex sha256 of AUDIT_EXPORT_PUBKEY_ED25519 (raw 32 bytes). */
export const AUDIT_EXPORT_PUBKEY_FINGERPRINT_HEX = '224ee86985c69cee4f616104da1819eeab13c1c640147b4ca55d874326c7b7cd';

/** Allowlist of historically-trusted audit-export pubkey fingerprints. */
export const KNOWN_AUDIT_EXPORT_PUBKEY_FINGERPRINTS: ReadonlySet<string> = new Set([
  "224ee86985c69cee4f616104da1819eeab13c1c640147b4ca55d874326c7b7cd"
]);
