// AUTO-GENERATED by scripts/bundle-license-pubkey.mjs at 2026-08-15T00:15:01.126Z.
// Source pem: packages/core/security/license-pubkey.pem
// RAW-bytes sha256: 18c0456789a70eeee28012719f04725f43f59e693f735227ff73f0475f2290e3
// DO NOT EDIT — regenerate via `node scripts/bundle-license-pubkey.mjs` or
// the prepublishOnly hook (which runs on every npm publish).

/**
 * Ed25519 public key for verifying signed /validate-key responses from
 * massu.ai. Used by packages/core/src/security/license-response-verifier.ts
 * to reject MITM / malicious-cloud-endpoint responses.
 *
 * P-H019 (plan-stage-c-high-batch / 1.10.5).
 *
 * To rotate (full runbook: docs/runbooks/license-response-signing-key-rotation.md):
 * regenerate the keypair, append the new RAW-bytes sha256 to
 * KNOWN_PUBKEY_FINGERPRINTS above (DO NOT delete the old entry during the grace
 * window), AND update PUBKEY_FINGERPRINT_HEX in
 * website/supabase/functions/validate-key/index.ts to the SAME new fingerprint
 * (it is stamped onto every response; a stale stamp is rejected by the client at
 * ed25519-envelope-verifier.ts:111). The order is load-bearing: the operator
 * installs the new secret AND deploys the fingerprint-updated function FIRST
 * (production signs with the new key), and only THEN is the new public key
 * vendored + this bundle regenerated + the client published. Bundling the new
 * client pubkey before production signs with it would make strict-mode clients
 * reject every response.
 */
export const LICENSE_PUBKEY_ED25519: Uint8Array = new Uint8Array([254, 188, 221, 150, 111, 252, 154, 100, 253, 247, 113, 192, 144, 224, 127, 160, 202, 111, 75, 40, 35, 169, 108, 89, 252, 250, 255, 233, 250, 120, 47, 160]);

/** Hex sha256 of LICENSE_PUBKEY_ED25519 (raw 32 bytes). */
export const LICENSE_PUBKEY_FINGERPRINT_HEX = '18c0456789a70eeee28012719f04725f43f59e693f735227ff73f0475f2290e3';

/** Allowlist of historically-trusted license pubkey fingerprints. */
export const KNOWN_LICENSE_PUBKEY_FINGERPRINTS: ReadonlySet<string> = new Set([
  "18a63d64fdec9e5a368fc45feaa49bed6ced815967e582bc7b8af534f22a9475",
  "18c0456789a70eeee28012719f04725f43f59e693f735227ff73f0475f2290e3"
]);
