// AUTO-GENERATED by scripts/bundle-license-pubkey.mjs at 2026-05-20T23:21:30.411Z.
// Source pem: packages/core/security/license-pubkey.pem
// RAW-bytes sha256: 18a63d64fdec9e5a368fc45feaa49bed6ced815967e582bc7b8af534f22a9475
// DO NOT EDIT — regenerate via `node scripts/bundle-license-pubkey.mjs` or
// the prepublishOnly hook (which runs on every npm publish).

/**
 * Ed25519 public key for verifying signed /validate-key responses from
 * massu.ai. Used by packages/core/src/security/license-response-verifier.ts
 * to reject MITM / malicious-cloud-endpoint responses.
 *
 * P-H019 (plan-stage-c-high-batch / 1.10.5).
 *
 * To rotate: regenerate the keypair via Node crypto.generateKeyPairSync,
 * update packages/core/security/license-pubkey.pem with the new public key,
 * append the new RAW-bytes sha256 to KNOWN_PUBKEY_FINGERPRINTS in
 * scripts/bundle-license-pubkey.mjs (DO NOT delete the old entry during
 * the rotation grace window), then run `node scripts/bundle-license-pubkey.mjs`.
 * Operator then updates the Supabase Edge Function env var
 * `LICENSE_RESPONSE_SIGNING_PRIVATE_KEY_B64` with the new private key.
 */
export const LICENSE_PUBKEY_ED25519: Uint8Array = new Uint8Array([39, 136, 108, 146, 85, 233, 119, 252, 223, 226, 123, 155, 234, 168, 200, 150, 36, 249, 174, 6, 130, 146, 125, 196, 136, 224, 202, 150, 53, 228, 114, 15]);

/** Hex sha256 of LICENSE_PUBKEY_ED25519 (raw 32 bytes). */
export const LICENSE_PUBKEY_FINGERPRINT_HEX = '18a63d64fdec9e5a368fc45feaa49bed6ced815967e582bc7b8af534f22a9475';

/** Allowlist of historically-trusted license pubkey fingerprints. */
export const KNOWN_LICENSE_PUBKEY_FINGERPRINTS: ReadonlySet<string> = new Set([
  "18a63d64fdec9e5a368fc45feaa49bed6ced815967e582bc7b8af534f22a9475"
]);
