// AUTO-GENERATED by scripts/bundle-promotion-pubkey.mjs at 2026-05-29T16:33:38.029Z.
// Source pem: packages/core/security/promotion-pubkey.pem
// RAW-bytes sha256: 0aeb8eff38f70fa3ed413ebf1fdc8cc00539ab7e76ea023e9424733847ad9956
// DO NOT EDIT — regenerate via `node scripts/bundle-promotion-pubkey.mjs` or
// the prepublishOnly hook (which runs on every npm publish).

/**
 * Ed25519 public key for verifying signed /promoted-rules differential-pull
 * responses from massu.ai. Used by
 * packages/core/src/security/promotion-envelope-verifier.ts to reject MITM /
 * malicious-cloud-endpoint / tampered-in-transit promotion envelopes.
 *
 * A team rule promotion is executable/behavioral config, so the verifier has
 * NO transition mode (unlike license-response-verifier): an unsigned or
 * invalid-signature envelope is DROPPED, never materialized.
 *
 * PA-003 (plan-2026-05-28-team-shared-rule-promotion).
 *
 * To rotate: regenerate the keypair via Node crypto.generateKeyPairSync,
 * update packages/core/security/promotion-pubkey.pem with the new public key,
 * append the new RAW-bytes sha256 to KNOWN_PUBKEY_FINGERPRINTS in
 * scripts/bundle-promotion-pubkey.mjs (DO NOT delete the old entry during
 * the rotation grace window), then run `node scripts/bundle-promotion-pubkey.mjs`.
 * Operator then updates the Supabase Edge Function env var
 * `PROMOTION_RESPONSE_SIGNING_PRIVATE_KEY_B64` with the new private key.
 */
export const PROMOTION_PUBKEY_ED25519: Uint8Array = new Uint8Array([196, 195, 157, 248, 40, 89, 113, 46, 171, 19, 150, 43, 134, 185, 131, 170, 187, 153, 213, 13, 96, 245, 110, 81, 12, 97, 194, 196, 64, 81, 169, 37]);

/** Hex sha256 of PROMOTION_PUBKEY_ED25519 (raw 32 bytes). */
export const PROMOTION_PUBKEY_FINGERPRINT_HEX = '0aeb8eff38f70fa3ed413ebf1fdc8cc00539ab7e76ea023e9424733847ad9956';

/** Allowlist of historically-trusted promotion pubkey fingerprints. */
export const KNOWN_PROMOTION_PUBKEY_FINGERPRINTS: ReadonlySet<string> = new Set([
  "0aeb8eff38f70fa3ed413ebf1fdc8cc00539ab7e76ea023e9424733847ad9956"
]);
