// AUTO-GENERATED by scripts/bundle-promotion-pubkey.mjs at 2026-07-24T16:31:19.071Z.
// Source pem: packages/core/security/promotion-pubkey.pem
// RAW-bytes sha256: b14e2a73e23c02891e976ec161d339da6c930266c0202828d3187a3bd6e5d83f
// DO NOT EDIT — regenerate via `node scripts/bundle-promotion-pubkey.mjs` or
// the prepublishOnly hook (which runs on every npm publish).

/**
 * Ed25519 public key for verifying signed /promoted-rules differential-pull
 * responses from massu.ai. Used by
 * packages/core/src/security/promotion-envelope-verifier.ts to reject MITM /
 * malicious-cloud-endpoint / tampered-in-transit promotion envelopes.
 *
 * A team rule promotion is executable/behavioral config, so the verifier has
 * NO transition mode (unlike license-response-verifier): an unsigned or
 * invalid-signature envelope is DROPPED, never materialized.
 *
 * PA-003 (plan-2026-05-28-team-shared-rule-promotion).
 *
 * To rotate: regenerate the keypair via Node crypto.generateKeyPairSync,
 * update packages/core/security/promotion-pubkey.pem with the new public key,
 * append the new RAW-bytes sha256 to KNOWN_PUBKEY_FINGERPRINTS in
 * scripts/bundle-promotion-pubkey.mjs (DO NOT delete the old entry during
 * the rotation grace window), then run `node scripts/bundle-promotion-pubkey.mjs`.
 * Operator then updates the Supabase Edge Function env var
 * `PROMOTION_RESPONSE_SIGNING_PRIVATE_KEY_B64` with the new private key.
 */
export const PROMOTION_PUBKEY_ED25519: Uint8Array = new Uint8Array([107, 161, 33, 17, 189, 44, 193, 128, 252, 155, 188, 236, 100, 163, 23, 146, 219, 155, 216, 139, 134, 72, 211, 182, 151, 122, 209, 151, 135, 65, 167, 26]);

/** Hex sha256 of PROMOTION_PUBKEY_ED25519 (raw 32 bytes). */
export const PROMOTION_PUBKEY_FINGERPRINT_HEX = 'b14e2a73e23c02891e976ec161d339da6c930266c0202828d3187a3bd6e5d83f';

/** Allowlist of historically-trusted promotion pubkey fingerprints. */
export const KNOWN_PROMOTION_PUBKEY_FINGERPRINTS: ReadonlySet<string> = new Set([
  "b14e2a73e23c02891e976ec161d339da6c930266c0202828d3187a3bd6e5d83f"
]);
