// AUTO-GENERATED by scripts/bundle-pubkey.mjs at 2026-05-09T20:42:44.314Z.
// Source pem: packages/core/security/registry-pubkey.pem
// RAW-bytes sha256: 3b6226d036c472e533110d11a7d0cd2773ce1d7d4f1003517d5bd69c5418ed4c
// DO NOT EDIT — regenerate via `node scripts/bundle-pubkey.mjs` or
// the prepublishOnly hook (which runs on every npm publish).

/**
 * Ed25519 public key for the Massu adapter registry (registry.massu.ai).
 * Used by packages/core/src/security/adapter-verifier.ts to verify signed
 * manifests. Plan 3c gap-29 (Phase D P4-003) generated and vendored.
 *
 * To rotate: regenerate the keypair (operator-only, store private in
 * macOS Keychain at `massu/registry/signing/private`), update
 * packages/core/security/registry-pubkey.pem with the new public key,
 * append the new RAW-bytes sha256 to KNOWN_PUBKEY_FINGERPRINTS in
 * scripts/bundle-pubkey.mjs (DO NOT delete the old entry — rotation grace
 * window per gap-54), then run `node scripts/bundle-pubkey.mjs`.
 */
export const REGISTRY_PUBKEY_ED25519: Uint8Array = new Uint8Array([12, 36, 232, 78, 159, 80, 198, 224, 21, 238, 144, 34, 84, 236, 219, 135, 224, 122, 164, 204, 0, 204, 155, 131, 30, 57, 213, 182, 61, 243, 141, 7]);

/** Hex sha256 of REGISTRY_PUBKEY_ED25519 (raw 32 bytes). */
export const REGISTRY_PUBKEY_FINGERPRINT_HEX = '3b6226d036c472e533110d11a7d0cd2773ce1d7d4f1003517d5bd69c5418ed4c';

/**
 * Allowlist of historically-trusted pubkey fingerprints. CR-9 audit L2
 * fix: the runtime verifier asserts that REGISTRY_PUBKEY_FINGERPRINT_HEX
 * is a member of this set; a bundled key that does not appear in the
 * allowlist refuses to load even if compiled in. Mirror of
 * KNOWN_PUBKEY_FINGERPRINTS in scripts/bundle-pubkey.mjs (kept in sync
 * by the bundle script's emit step). Append on rotation; never remove
 * during the grace window.
 */
export const KNOWN_PUBKEY_FINGERPRINTS: ReadonlySet<string> = new Set([
  "3b6226d036c472e533110d11a7d0cd2773ce1d7d4f1003517d5bd69c5418ed4c"
]);
