// Copyright (c) 2026 Massu. All rights reserved.
// Licensed under BSL 1.1 - see LICENSE file for details.
// @scanner-allow:large-file the four-destination apply transaction + the
// team/pack apply gate (CR-54/55/57) + structural payload validation + the
// destination-fidelity assert (curated-rule-packs review) are one cohesive
// security-critical chokepoint; snapshot/hardened/preview concerns are already
// extracted to sibling modules. Splitting the gate from the transaction it
// guards would scatter the security boundary. Marker added when the fidelity
// fix pushed it just over the 1000-LOC cap.

// plan-v0.2-interactive-rule-approval P-C-004: atomic-write rule applier.
// Implements the §5 four-step SQLite transaction with snapshot-set
// compensating-action rollback. Phase C wires only the `corrections-md`
// destination; Phase D extends to `pattern-scanner`, `claude-md-cr`, and
// `custom-destination`.

import { readFileSync, writeFileSync, existsSync, unlinkSync, mkdirSync } from 'fs';
import { join, dirname, isAbsolute, relative } from 'path';
import {
  assertContainedIn,
  assertSingleLine,
  atomicWriteFileSync,
  deriveSlug as sharedDeriveSlug,
} from './lib/safe-write.ts';
import { formatCorrectionEntry } from './lib/corrections-md.ts';
import { mintAuthorship, RENDER_MAC_KEY } from './memory-authorship.ts';
import {
  readMemoryIndex,
  readRegionLines,
  renderRegion,
  writeMemoryIndex,
  RegionRefused,
  MemoryIndexMissing,
  DEFAULT_MAX_REGION_LINES,
} from './memory-index-region.ts';
import { homedir } from 'os';
import { createHash } from 'crypto';
import type Database from 'better-sqlite3';
import { getProjectRoot } from './config.ts';
import { encodeMemoryDirName } from './lib/memory-path.ts';
import { logAuditEntry, type AuditEntry } from './audit-trail.ts';
import { renderTemplate, type TemplateVars } from './template-renderer.ts';
import type { CustomDestinationConfig } from './rule-classifier.ts';
import {
  assertAutoLearningEntitled,
  entitledForTeamSharedPromotion,
  teamSharedPromotionUpgradeMessage,
} from './auto-learning-entitlement.ts';
import { enqueueTeamPromotion } from './memory-db.ts';
import { recordApprovalFunnelEvent, recordDismissalFunnelEvent } from './rule-candidate-funnel.ts';

// SEC-01 fix: candidate IDs are sha-keyed via `hashPrompt()` which returns
// 16 hex chars (sha-256 truncated). Reject any other shape at the I/O
// boundary so a malicious `<id>` like `../../../tmp/foo` cannot escape
// the .massu/rule-candidates directory and cause arbitrary unlinkSync /
// audit_log poisoning.
const CANDIDATE_ID_PATTERN = /^[a-f0-9]{16}$/;
// SEC-03 fix: slug enters the auto-generated bash + a TypeScript filename
// at the same character set deriveSlug() outputs ([a-z0-9_]). Always
// re-sanitize regardless of caller-provided value.
const SLUG_ALLOWED = /^[a-z0-9_]+$/;
// PR-03 (Phase 1.5 pattern review): co-located with other top-of-file
// constants rather than declared mid-file at the writePatternScanner
// call-site (was at line 526). Marker prefix for auto-generated
// pattern-scanner check blocks; checked by Check 29 + drift-guard mirror.
const SCANNER_AUTOGEN_MARKER_PREFIX = '# auto-generated by /massu-rule approve';

export class InvalidCandidateIdError extends Error {
  constructor(public readonly id: string) {
    super(`candidate id "${id}" is not a 16-hex-char sha-keyed identifier`);
    this.name = 'InvalidCandidateIdError';
  }
}

export class InvalidSlugError extends Error {
  constructor(public readonly slug: string) {
    super(`slug "${slug}" contains characters outside [a-z0-9_]`);
    this.name = 'InvalidSlugError';
  }
}

export class CandidatePayloadValidationError extends Error {
  constructor(public readonly issue: string) {
    super(`candidate payload validation failed: ${issue}`);
    this.name = 'CandidatePayloadValidationError';
  }
}

export type RuleDestination =
  | 'corrections-md'
  | 'pattern-scanner'
  | 'claude-md-cr'
  | 'custom-destination';

/** The exhaustive set of valid {@link RuleDestination} values (validation SoT). */
const ALL_RULE_DESTINATIONS: readonly RuleDestination[] = ['corrections-md', 'pattern-scanner', 'claude-md-cr', 'custom-destination'];

/** Type guard: is `value` one of the four known {@link RuleDestination}s? */
export function isRuleDestination(value: unknown): value is RuleDestination {
  return typeof value === 'string' && (ALL_RULE_DESTINATIONS as readonly string[]).includes(value);
}

/**
 * H1 SoT (PB-005, plan-2026-05-28-team-shared-rule-promotion): the ONLY
 * destinations that may propagate cross-seat in team-shared promotion v1. Both
 * are NON-EXECUTING text/governance a human reads before it takes effect.
 * `pattern-scanner` (arbitrary bash) and `custom-destination` (arbitrary file
 * write) — the genuine RCE/destructive classes — are deliberately EXCLUDED:
 * they remain available for a seat's OWN local promotions but are never
 * published, pulled, or applied from a team origin. This array MUST stay in
 * lockstep with the server `/sync` ingest allowlist, the `/promoted-rules`
 * filter, and the `promoted_rules.destination` CHECK constraint (migration 043).
 * The PB-007 drift-guard + pattern-scanner Check 32 pin it to exactly these two.
 */
export const TEAM_SHAREABLE_DESTINATIONS: readonly RuleDestination[] = [
  'corrections-md',
  'claude-md-cr',
];

/** Is `destination` one of the H1 cross-seat-propagatable destinations? */
export function isTeamShareableDestination(destination: string): destination is RuleDestination {
  return (TEAM_SHAREABLE_DESTINATIONS as readonly string[]).includes(destination);
}

// PA3-003/004: the hardened (executable-destination) cross-seat primitives live in
// `rule-candidate-hardened.ts` (cohesive concern, keeps this module under the
// 1000-LOC cap). Imported here for the apply-gate + publish branch; other sites
// (team-rule-sync, drift-guard, preview) import them from that canonical module.
import {
  isHardenedShareableDestination,
  validateHardenedApplyGate,
  type ReviewAttestation,
} from './rule-candidate-hardened.ts';

// PA1-003 (plan-2026-06-01-enterprise-governance-audit-export): the generalized
// org-level N-of-M governance gate lives in the same canonical hardened module
// (validateHardenedApplyGate is its N=2 special case). Re-exported through the
// applier's public API so the /massu-rule approvals surface + the governance
// drift-guard reach it via the applier without a duplicate import path.
export {
  validateGovernanceGate,
  roleRank,
  type GovernancePolicy,
  type GovernanceApprovals,
  type PromoterRole,
} from './rule-candidate-hardened.ts';

/**
 * PB-004: provenance for a candidate materialized from a TEAM origin (pulled
 * from the cloud by `team-rule-sync`). A team-origin sidecar is only ever
 * WRITTEN after the pull path verified the Ed25519 envelope, so
 * `signature_verified` is always `true` for legitimately-materialized
 * candidates; the applier's team-origin gate refuses any team candidate whose
 * `signature_verified !== true` (a hand-forged sidecar). Local (Phase 1)
 * candidates omit this field entirely (back-compat).
 */
export interface RuleCandidateProvenance {
  /**
   * P2-003 (curated-rule-packs): `'pack'` marks a candidate materialized from an
   * installed rule pack (pulled + Ed25519-verified by `rule-pack-sync`). It rides
   * the SAME apply-gate as a team origin (tier≥Team + signature_verified +
   * shareable/hardened destination) and is likewise excluded from the cross-seat
   * re-publish funnel (we don't echo what we pulled).
   *
   * TAXONOMY RATIONALE (ARCH — intentional): `team` and `pack` are treated
   * IDENTICALLY by the apply gate (both alias `entitledForTeamSharedPromotion`) —
   * same Team-gated, Ed25519-signed, cross-seat security posture. The origin tag
   * distinguishes only PROVENANCE + DISPLAY: `pack` carries {@link pack_slug}/
   * {@link pack_version}; `team` carries {@link promoted_by}. NO separate pack
   * entitlement by design — Team is the correct gate for both.
   */
  origin: 'team' | 'pack';
  org_id: string;
  promoted_by: string;
  promoted_at: string;
  signature_verified: boolean;
  /**
   * PA3-003: present (true) only on HARDENED team candidates (executable
   * destinations propagated via the hardened-review path). Absent/false on the
   * Phase-2 non-executing destinations. A hardened candidate requires the extra
   * apply-gate checks (PA3-004): tier≥Team + signature_verified + a valid
   * {@link ReviewAttestation} with a distinct second operator + render-only ack.
   */
  hardened?: boolean;
  /** PA3-003: the two-operator + render-only-preview attestation (hardened rows only). */
  review_attestation?: ReviewAttestation;
  /**
   * P2-002 (curated-rule-packs): the marketplace pack slug a `origin:'pack'`
   * candidate was materialized from (by `rule-pack-sync.pullInstalledPackRules`).
   * Display-only provenance; absent on `origin:'team'` candidates.
   */
  pack_slug?: string;
  /**
   * P2-002 (curated-rule-packs): the pack's `current_version` at materialize time.
   * Paired with {@link pack_slug} for the `list` "FROM PACK `<slug>@<version>`"
   * provenance flag. Absent on `origin:'team'` candidates.
   */
  pack_version?: string;
}

export interface RuleCandidatePayload {
  prompt: string;
  prompt_hash: string;
  score: number;
  signals: Array<{ name: string; baseWeight: number; applied: number; evidence?: string }>;
  prior_turn_files: string[];
  timestamp: string;
  session_id: string;
  /** PB-004: present only on team-origin candidates (see {@link RuleCandidateProvenance}). */
  provenance?: RuleCandidateProvenance;
  /**
   * ARCH-FIX (destination fidelity): the AUTHORITATIVE destination the publisher
   * (team) / pack author decided, written VERBATIM into the sidecar (and carried
   * through migration 048's mapping). A provenance-bearing (team|pack) candidate
   * MUST apply to THIS destination — `approve` must NOT re-classify it (which
   * would silently re-route claude-md-cr → corrections-md, or downgrade an
   * executable rule off the hardened path). The apply gate refuses with zero
   * mutation when `opts.destination !== candidate.destination`. Absent on LOCAL
   * candidates (which DO classify via `classifyCandidate()`).
   */
  destination?: RuleDestination;
  /** ARCH-FIX: authoritative draft body authored alongside {@link destination}; passed through as `opts.draftText` for provenance candidates. Absent on LOCAL. */
  draft_text?: string;
}

export interface ApplyOptions {
  candidateId: string;
  destination: RuleDestination;
  draftText: string;
  /**
   * Slug used for the new `memory/feedback_<slug>.md` file.
   * If absent, derived from the candidate prompt.
   */
  slug?: string;
  /**
   * Project root override (tests use this to point at a tmpdir).
   * Defaults to `getProjectRoot()`.
   */
  projectRoot?: string;
  /**
   * Home dir override (tests use this to redirect `.claude/projects/...`
   * into a tmpdir rather than the real `~/.claude`).
   * Defaults to `os.homedir()`.
   */
  home?: string;
  /**
   * Pattern-scanner destination: the next Check number to allocate. The
   * applier appends `Check N: <description>` block. Caller is responsible
   * for computing N (typically scanner_max_check + 1).
   */
  patternScannerCheckNumber?: number;
  /**
   * Claude-md-cr destination: the next CR number to allocate (e.g. 54).
   */
  claudeMdCrNumber?: number;
  /**
   * Custom-destination: the matched config entry (passed through from
   * classifyCandidate when destination === 'custom-destination'). The
   * applier renders `entry.template` via `renderTemplate()` using the
   * candidate's score / signals / prompt as vars.
   */
  customDestination?: CustomDestinationConfig;
  /**
   * PA3-004: present when a Team+ seat promotes a LOCAL rule to a HARDENED
   * (executable) destination and wants to share it cross-seat. The publisher's
   * review attestation is enqueued so the server CHECK (hardened rows require a
   * review_attestation) is satisfiable. Absent for non-hardened promotions; a
   * hardened destination without it is NOT published cross-seat.
   */
  reviewAttestation?: ReviewAttestation;
}

export interface ApplyResult {
  ok: boolean;
  /**
   * `true` when the UNIQUE index tripped on `prompt_hash` — promotion
   * already happened and the second call was a no-op.
   */
  idempotent_noop?: boolean;
  audit_log_id?: number;
  error?: string;
  /**
   * `true` when the promotion was refused because the current tier is below
   * the auto-learning minimum (Pro). On refusal, ZERO DB/file mutation
   * occurs — the gate runs before `takeSnapshots`/`BEGIN`. The `error` field
   * carries the generic upgrade message (CR-54).
   */
  tier_refused?: boolean;
  /**
   * PB-005: `true` when this promotion was ALSO enqueued for team-shared
   * propagation (Team+ seat AND a shareable destination). The publish is a
   * best-effort, post-COMMIT side-effect — a `false`/absent value never fails
   * the local promotion. Pro seats and non-shareable destinations are always
   * `false`.
   */
  team_shared?: boolean;
}

/**
 * Resolve the absolute path to the project's `memory/` directory under
 * `<home>/.claude/projects/<encoded-root>/memory/`. Single canonical helper —
 * never call `path.resolve('memory/...')` from a relative cwd.
 */
export function resolveMemoryDir(projectRoot = getProjectRoot(), home = homedir()): string {
  return join(home, '.claude', 'projects', encodeMemoryDirName(projectRoot), 'memory');
}

export function resolveMemoryIndexPath(projectRoot = getProjectRoot(), home = homedir()): string {
  return join(resolveMemoryDir(projectRoot, home), 'MEMORY.md');
}

export class MemoryIndexMissingError extends Error {
  constructor(public readonly path: string) {
    super(`MEMORY.md missing at ${path} — v0.2 requires the canonical memory index. Create it via \`mkdir -p ${dirname(path)} && echo '# Memory Index' > ${path}\` or run \`/massu-bearings\``);
    this.name = 'MemoryIndexMissingError';
  }
}

export class CandidateNotFoundError extends Error {
  constructor(public readonly path: string) {
    super(`candidate sidecar not found: ${path}`);
    this.name = 'CandidateNotFoundError';
  }
}

/**
 * Sanitize a correction prompt into a snake_case slug suitable for a
 * `feedback_<slug>.md` filename. Strips non-alphanumeric, collapses
 * whitespace, lowercases, caps at 60 chars.
 */
export function deriveSlug(prompt: string): string {
  // ONE slugger, in lib/safe-write.ts. Re-exported here so existing callers are
  // unchanged — a second implementation is how two writers end up disagreeing about
  // what a file is called.
  return sharedDeriveSlug(prompt);
}

/**
 * B-16 — add ONE line to MEMORY.md's managed region, bounded and de-duplicated.
 *
 * This REPLACES `appendMemoryIndexLine` as the applier's write path. The old unbounded
 * EOF append grew MEMORY.md forever, and MEMORY.md is loaded into EVERY turn of EVERY
 * session — a permanent, compounding context tax that B-05's cap would have bounded on
 * the renderer's side only.
 *
 * Throws if the region is unavailable (damaged sentinels / no MEMORY.md). The caller
 * catches and proceeds: a rule promotion must not fail because MEMORY.md is damaged.
 */
export function writeIndexLineInRegion(indexPath: string, line: string): void {
  const pre = readMemoryIndex(indexPath);
  if (pre === undefined) {
    // NEVER create MEMORY.md (B-17). The applier already refused to; the renderer matches.
    throw new MemoryIndexMissing('MEMORY.md does not exist — index line skipped (file still written)');
  }

  const existing = readRegionLines(pre);
  if (existing.includes(line)) return; // idempotent: a re-promotion must not duplicate

  const next = [...existing, line].slice(-DEFAULT_MAX_REGION_LINES);
  const post = renderRegion(pre, next); // throws RegionRefused on damaged sentinels
  if (post !== pre) writeMemoryIndex(indexPath, pre, post); // asserts the post-write invariant
}

/**
 * @deprecated B-16 — RETIRED as a write path. Its unbounded EOF append is exactly the
 * growth B-05 bounds on the renderer's side, and leaving it live would bound only half
 * of MEMORY.md's growth. Retained ONLY as the line FORMATTER's hardened contract (A-13)
 * and for its tests; a drift-guard asserts it has no caller that writes outside the
 * managed region. Use `writeIndexLineInRegion`.
 */
export function appendMemoryIndexLine(indexPath: string, line: string): void {
  // A-13 — the helper enforces its own contract now.
  //
  // It did NO newline stripping, and was safe only by accident of its single
  // callsite, which happens to sanitize. MEMORY.md is auto-loaded into EVERY
  // session as trusted context, so a `\n` in a caller-supplied title injects
  // arbitrary markdown into the model's context forever. The append-only
  // invariant would not even notice: `post === pre + line + '\n'` holds no
  // matter what is inside `line`. The renderer (4B) becomes a SECOND caller, so
  // a latent hole becomes a live one — do not rely on callsite discipline twice.
  assertSingleLine(line);

  const pre = readFileSync(indexPath, 'utf-8');
  const sep = pre.endsWith('\n') ? '' : '\n';
  const next = pre + sep + line + '\n';
  // A-14 — atomic. A truncating writeFileSync loses MEMORY.md on a crash/ENOSPC
  // mid-write; this is the operator's 17KB hand-curated index.
  atomicWriteFileSync(indexPath, next);
}

// Snapshot/restore helpers live in ./rule-candidate-snapshot.ts (extracted to
// keep this module ≤999 LOC, Check 21). Imported for local use AND re-exported
// so existing import paths (and the applier test) are unchanged.
import { takeSnapshots, restoreSnapshots, type Snapshot } from './rule-candidate-snapshot.ts';
export { takeSnapshots, restoreSnapshots, type Snapshot };

interface CorrectionsMdPaths {
  correctionsMd: string;
  feedbackMd: string;
  memoryIndex: string;
}

function correctionsMdTargets(slug: string, projectRoot: string, home: string): CorrectionsMdPaths {
  const dir = resolveMemoryDir(projectRoot, home);
  return {
    correctionsMd: join(dir, 'corrections.md'),
    feedbackMd: join(dir, `feedback_${slug}.md`),
    memoryIndex: join(dir, 'MEMORY.md'),
  };
}

/**
 * Read a candidate sidecar from `<projectRoot>/.massu/rule-candidates/`.
 *
 * SEC-01: validates `candidateId` against the sha-keyed shape before
 * touching the filesystem, refusing path-traversal attempts.
 * SEC-04: validates the parsed payload's required fields at runtime —
 * a planted or corrupted sidecar cannot inject untyped data into the
 * audit_log metadata / UNIQUE INDEX key.
 */
export function readCandidate(candidateId: string, projectRoot = getProjectRoot()): RuleCandidatePayload {
  if (!CANDIDATE_ID_PATTERN.test(candidateId)) {
    throw new InvalidCandidateIdError(candidateId);
  }
  const path = join(projectRoot, '.massu', 'rule-candidates', `${candidateId}.json`);
  if (!existsSync(path)) throw new CandidateNotFoundError(path);
  const raw = readFileSync(path, 'utf-8');
  let parsed: unknown;
  try { parsed = JSON.parse(raw); } catch (err) {
    throw new CandidatePayloadValidationError(`JSON parse: ${err instanceof Error ? err.message : String(err)}`);
  }
  return validateCandidatePayload(parsed);
}

function validateCandidatePayload(raw: unknown): RuleCandidatePayload {
  if (!raw || typeof raw !== 'object') {
    throw new CandidatePayloadValidationError('payload is not an object');
  }
  const r = raw as Record<string, unknown>;
  if (typeof r.prompt !== 'string' || r.prompt.length === 0) {
    throw new CandidatePayloadValidationError('prompt must be a non-empty string');
  }
  if (typeof r.prompt_hash !== 'string' || !/^[a-f0-9]{16}$/.test(r.prompt_hash)) {
    throw new CandidatePayloadValidationError('prompt_hash must be 16 hex chars');
  }
  if (typeof r.score !== 'number' || r.score < -200 || r.score > 200 || !Number.isFinite(r.score)) {
    throw new CandidatePayloadValidationError('score must be a finite number in [-200, 200]');
  }
  if (!Array.isArray(r.signals)) {
    throw new CandidatePayloadValidationError('signals must be an array');
  }
  for (const s of r.signals) {
    if (!s || typeof s !== 'object') throw new CandidatePayloadValidationError('signal entry not an object');
    const sig = s as Record<string, unknown>;
    if (typeof sig.name !== 'string') throw new CandidatePayloadValidationError('signal.name must be a string');
    if (typeof sig.baseWeight !== 'number') throw new CandidatePayloadValidationError('signal.baseWeight must be a number');
    if (typeof sig.applied !== 'number') throw new CandidatePayloadValidationError('signal.applied must be a number');
  }
  if (!Array.isArray(r.prior_turn_files)) {
    throw new CandidatePayloadValidationError('prior_turn_files must be an array');
  }
  if (typeof r.timestamp !== 'string') {
    throw new CandidatePayloadValidationError('timestamp must be a string');
  }
  if (typeof r.session_id !== 'string') {
    throw new CandidatePayloadValidationError('session_id must be a string');
  }
  // PB-004: validate optional team provenance when present. Local candidates
  // omit it (back-compat); a team-origin sidecar MUST carry a well-formed block.
  if (r.provenance !== undefined) {
    if (!r.provenance || typeof r.provenance !== 'object') {
      throw new CandidatePayloadValidationError('provenance must be an object when present');
    }
    const p = r.provenance as Record<string, unknown>;
    if (p.origin !== 'team' && p.origin !== 'pack') {
      throw new CandidatePayloadValidationError("provenance.origin must be 'team' or 'pack'");
    }
    if (typeof p.org_id !== 'string' || p.org_id.length === 0) {
      throw new CandidatePayloadValidationError('provenance.org_id must be a non-empty string');
    }
    if (typeof p.promoted_by !== 'string' || p.promoted_by.length === 0) {
      throw new CandidatePayloadValidationError('provenance.promoted_by must be a non-empty string');
    }
    if (typeof p.promoted_at !== 'string') {
      throw new CandidatePayloadValidationError('provenance.promoted_at must be a string');
    }
    if (typeof p.signature_verified !== 'boolean') {
      throw new CandidatePayloadValidationError('provenance.signature_verified must be a boolean');
    }
    // ARCH-FIX (destination fidelity): a provenance-bearing (team|pack) sidecar MUST
    // carry the publisher / pack author's AUTHORITATIVE destination so the apply gate
    // can enforce it verbatim (never re-classified). A planted sidecar that omits it
    // (to force re-classification) is rejected here at the I/O boundary.
    if (!isRuleDestination(r.destination)) {
      throw new CandidatePayloadValidationError('provenance-bearing candidate must declare a valid destination');
    }
    if (r.draft_text !== undefined && typeof r.draft_text !== 'string') {
      throw new CandidatePayloadValidationError('draft_text must be a string when present');
    }
  } else if (r.destination !== undefined && !isRuleDestination(r.destination)) {
    // A LOCAL candidate may omit destination (classified at approve time); if present it must be valid.
    throw new CandidatePayloadValidationError('destination, when present, must be a valid RuleDestination');
  }
  return r as unknown as RuleCandidatePayload;
}

/**
 * Apply a rule candidate per plan §5: four-step transaction (audit row
 * INSERT → destination edits → MEMORY.md append → candidate delete).
 * On ANY error: SQLite ROLLBACK + per-file snapshot restore + candidate
 * file left in place + failure appended to `.failures.jsonl`.
 *
 * Dispatches to one of four destination writers based on `opts.destination`:
 *   - `corrections-md`: appends to `memory/corrections.md` + writes feedback file
 *   - `pattern-scanner`: appends Check block to `massu-pattern-scanner.sh` + drift-guard sidecar
 *   - `claude-md-cr`: splices Canonical Rules table row + appends CR body
 *   - `custom-destination`: renders RCE-safe template to the config-provided path
 *
 * @param db Caller-owned better-sqlite3 handle — applier does NOT close it.
 *           Caller is responsible for `db.close()` after this call returns.
 *           The applier wraps its writes in `BEGIN ... COMMIT` / `ROLLBACK`
 *           on the same handle.
 * @param opts See {@link ApplyOptions}. `candidateId` MUST match
 *             `/^[a-f0-9]{16}$/` (SEC-01); slug MUST sanitize to
 *             `[a-z0-9_]+` (SEC-03); destination-specific args
 *             (`patternScannerCheckNumber`, `claudeMdCrNumber`,
 *             `customDestination`) MUST be provided for the matching
 *             destination.
 * @returns `{ok, audit_log_id?, idempotent_noop?, error?}`.
 *          `idempotent_noop=true` when the UNIQUE INDEX on
 *          `audit_log.metadata.prompt_hash` trips (rule already promoted).
 */
export async function applyRuleCandidate(
  db: Database.Database,
  opts: ApplyOptions
): Promise<ApplyResult> {
  // CR-54 (plan-2026-05-27-tier-gate-auto-learning): auto-learning promotion
  // is a Pro+ feature. Resolve entitlement INSIDE the chokepoint (the caller
  // cannot inject a forged tier) and refuse BEFORE any candidate read,
  // snapshot, or BEGIN — zero DB/file mutation on refusal. Fail-closed.
  const ent = await assertAutoLearningEntitled();
  if (!ent.entitled) {
    return { ok: false, error: ent.message, tier_refused: true };
  }

  // SEC-01: validate the candidateId shape before any filesystem access.
  if (!CANDIDATE_ID_PATTERN.test(opts.candidateId)) {
    throw new InvalidCandidateIdError(opts.candidateId);
  }
  const projectRoot = opts.projectRoot ?? getProjectRoot();
  const home = opts.home ?? homedir();
  const candidate = readCandidate(opts.candidateId, projectRoot);

  // PB-005: team-origin apply gate. A candidate materialized from a TEAM origin
  // (a teammate's promotion pulled via team-rule-sync) may only be applied by a
  // Team+ seat, MUST carry verified provenance, and MUST target a shareable
  // destination (H1). All three checks run BEFORE takeSnapshots / BEGIN → zero
  // DB/file mutation on refusal. This is the apply-time backstop to the trust
  // model: even a hand-forged team sidecar (signature_verified:false) or a
  // smuggled non-shareable destination is refused here.
  // TAXONOMY (ARCH — intentional): `team` and `pack` share this ONE gate and both
  // alias `entitledForTeamSharedPromotion` — same Team-gated, signed, cross-seat
  // security posture; origin distinguishes only provenance + display (see
  // {@link RuleCandidateProvenance.origin}). No separate pack entitlement by design.
  if (candidate.provenance?.origin === 'team' || candidate.provenance?.origin === 'pack') {
    const provOrigin = candidate.provenance.origin;
    // ARCH-FIX (destination fidelity): the publisher / pack author already decided
    // the authoritative destination (stored verbatim, carried through migration
    // 048's mapping). Refuse — with ZERO mutation, BEFORE takeSnapshots / BEGIN —
    // any attempt to apply a provenance-bearing candidate to a destination other
    // than its authored one, so silent re-routing (claude-md-cr → corrections-md,
    // or an executable rule downgraded off the hardened path) is structurally
    // impossible. Validation already guarantees `candidate.destination` is set.
    if (candidate.destination !== undefined && opts.destination !== candidate.destination) {
      return {
        ok: false,
        error: 'destination mismatch: provenance-bearing candidate must apply to its authored destination',
      };
    }
    if (!entitledForTeamSharedPromotion(ent.currentTier)) {
      return { ok: false, error: teamSharedPromotionUpgradeMessage(ent.currentTier), tier_refused: true };
    }
    if (candidate.provenance.signature_verified !== true) {
      return { ok: false, error: `${provOrigin}-origin rule candidate has unverified provenance — refusing to apply` };
    }
    if (isTeamShareableDestination(opts.destination)) {
      // Phase-2 non-executing path — no extra checks beyond tier + signature.
    } else if (isHardenedShareableDestination(opts.destination)) {
      // PA3-004 hardened path: an executable destination from a team origin may
      // apply ONLY with verified hardened provenance + a valid two-operator,
      // render-only-preview attestation (operator decision 2026-06-01). Checked
      // BEFORE takeSnapshots / BEGIN → zero mutation on refusal.
      const gateErr = validateHardenedApplyGate(candidate.provenance);
      if (gateErr) return { ok: false, error: gateErr };
    } else {
      return { ok: false, error: `${provOrigin}-origin candidate has a non-shareable destination — refusing to apply` };
    }
  }

  // SEC-03: always re-sanitize the slug regardless of caller source.
  // Caller-supplied opts.slug is treated as a hint, not authority.
  const slug = opts.slug ? deriveSlug(opts.slug) : deriveSlug(candidate.prompt);
  if (!SLUG_ALLOWED.test(slug)) {
    throw new InvalidSlugError(slug);
  }
  const memoryIndex = resolveMemoryIndexPath(projectRoot, home);

  // Preconditions: MEMORY.md MUST exist regardless of destination — Step 3
  // of every transaction appends an index line. Refuse rather than create
  // silently (plan §5: a system that silently creates MEMORY.md mid-tx
  // would mask a project-misconfiguration bug class).
  if (!existsSync(memoryIndex)) {
    throw new MemoryIndexMissingError(memoryIndex);
  }

  let destTargets: DestinationTargets;
  try {
    destTargets = computeDestinationTargets(opts, candidate, slug, projectRoot, home);
  } catch (err) {
    return { ok: false, error: err instanceof Error ? err.message : String(err) };
  }

  const candidatePath = join(projectRoot, '.massu', 'rule-candidates', `${opts.candidateId}.json`);
  const snapshot: Snapshot = takeSnapshots([
    ...destTargets.paths,
    memoryIndex,
  ]);

  db.exec('BEGIN');
  let auditRowId: number | undefined;
  // B-16: set when the MEMORY.md pointer could not be written (damaged sentinels, no
  // MEMORY.md). The promotion still succeeds — the pointer is recoverable, and failing a
  // rule promotion because an unrelated file is damaged would be the wrong trade.
  let indexLineSkipped: string | undefined;
  try {
    // Step 1: INSERT INTO audit_log — UNIQUE index trips on duplicate.
    const auditEntry: AuditEntry = {
      eventType: 'rule_promoted',
      actor: 'human',
      sessionId: candidate.session_id,
      filePath: destTargets.primary,
      metadata: {
        candidate_id: opts.candidateId,
        prompt_hash: candidate.prompt_hash,
        score: candidate.score,
        classification: opts.destination,
        cr_assigned: opts.claudeMdCrNumber ?? null,
        recurrence_count: 0,
      },
    };
    try {
      logAuditEntry(db, auditEntry);
      auditRowId = (db.prepare('SELECT last_insert_rowid() AS id').get() as { id: number }).id;
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      if (/UNIQUE constraint failed/i.test(msg)) {
        db.exec('ROLLBACK');
        return { ok: true, idempotent_noop: true };
      }
      throw err;
    }

    // Step 2: destination edit — dispatched by destination class.
    writeDestination(opts, candidate, slug, destTargets, auditRowId);

    // Step 3: MEMORY.md — INSIDE THE MANAGED REGION (B-16).
    //
    // This was an UNBOUNDED append at EOF. MEMORY.md is auto-loaded into every turn of
    // every session, so an unbounded index is a permanent, compounding context tax — and
    // B-05's bound would have bounded only HALF the growth while the applier grew the
    // other half without limit. The applier's line now lives in the same region, under
    // the same cap and the same eviction policy, taken under the same cross-process lock.
    //
    // FAILURE POLICY (B-16): if the region is unavailable (damaged sentinels, a busy
    // lock, or no MEMORY.md at all), the applier STILL writes its feedback_<slug>.md and
    // simply logs the missing index line. A rule promotion must not fail because
    // MEMORY.md is damaged — the pointer is recoverable, the promotion is not.
    const indexLine = assertSingleLine(
      `- [${slug}](feedback_${slug}.md) — ${candidate.prompt.replace(/\n+/g, ' ').slice(0, 100)}`
    );
    //
    // ⚠ TWO DIFFERENT FAILURES, TWO DIFFERENT ANSWERS — do not collapse them:
    //   - The region is UNPARSEABLE (damaged sentinels) or MEMORY.md is absent. That is
    //     a STRUCTURE problem with a file we are not required to have. Skip the pointer,
    //     keep the promotion. This is B-16's stated failure policy.
    //   - The write itself FAILS (EACCES on a read-only MEMORY.md, ENOSPC, EIO). That is
    //     a genuine I/O failure, and the shipped contract — asserted by
    //     `rule-candidate-applier-extended.test.ts` — is that the whole 4-step
    //     transaction ROLLS BACK. Swallowing it would leave a promoted rule with a
    //     half-written destination and no way back.
    try {
      writeIndexLineInRegion(memoryIndex, indexLine);
    } catch (err) {
      if (err instanceof RegionRefused || err instanceof MemoryIndexMissing) {
        indexLineSkipped = (err as Error).message;
      } else {
        throw err; // a real I/O failure ⇒ roll the whole promotion back
      }
    }

    // Step 4: consume the candidate file.
    if (existsSync(candidatePath)) unlinkSync(candidatePath);

    db.exec('COMMIT');

    // PB-005: team-shared publish branch. After a successful LOCAL promotion, a
    // Team+ seat enqueues the promotion for cross-seat propagation IF the
    // destination is shareable (H1: corrections-md / claude-md-cr only).
    // Best-effort and post-COMMIT — a failure here NEVER fails the local
    // promotion. Team- and pack-ORIGIN candidates are skipped: we don't re-publish
    // what we pulled (no echo loop). `ent` is the already-resolved entitlement (no
    // new tier resolution — the caller cannot inject a forged tier).
    let teamShared = false;
    const localOrigin =
      candidate.provenance?.origin !== 'team' && candidate.provenance?.origin !== 'pack';
    const entitledTeam = entitledForTeamSharedPromotion(ent.currentTier);
    const nonHardenedShare = isTeamShareableDestination(opts.destination);
    // PA3-004: a HARDENED (executable) destination publishes cross-seat ONLY when
    // the publisher supplied a review_attestation (which the server requires for
    // hardened rows — migration 045 CHECK). The server independently re-checks the
    // org opt-in (default OFF) on ingest; the org opt-in is the REAL boundary.
    const hardenedShare =
      isHardenedShareableDestination(opts.destination) && opts.reviewAttestation != null;
    if (localOrigin && entitledTeam && (nonHardenedShare || hardenedShare)) {
      try {
        enqueueTeamPromotion(db, {
          prompt_hash: candidate.prompt_hash,
          destination: opts.destination,
          draft_text: opts.draftText,
          score: candidate.score,
          signals: candidate.signals,
          content_hash: createHash('sha256')
            .update(`${opts.destination}\n${opts.draftText}`)
            .digest('hex'),
          ...(hardenedShare
            ? { hardened: true, review_attestation: opts.reviewAttestation }
            : {}),
        });
        teamShared = true;
      } catch {
        // best-effort — the local promotion is already committed
      }
    }

    // P1-002: capture the APPROVED funnel event (post-COMMIT, best-effort; skip
    // team-origin so the funnel counts only this seat's own proposals).
    if (localOrigin) recordApprovalFunnelEvent(db, candidate.prompt_hash, opts.destination, candidate.score, entitledTeam);
    return { ok: true, audit_log_id: auditRowId, team_shared: teamShared };
  } catch (err) {
    db.exec('ROLLBACK');
    restoreSnapshots(snapshot);
    const msg = err instanceof Error ? err.message : String(err);
    appendFailureLog(projectRoot, {
      candidate_id: opts.candidateId,
      destination: opts.destination,
      error: msg,
      timestamp: new Date().toISOString(),
    });
    return { ok: false, error: msg };
  }
}

// ============================================================
// Destination targets + writers (P-D-001)
// ============================================================

interface DestinationTargets {
  /** Primary file logged on the audit_log row's file_path. */
  primary: string;
  /** All files this destination writes — input to takeSnapshots. */
  paths: string[];
}

export class DestinationConfigError extends Error {
  constructor(msg: string) { super(msg); this.name = 'DestinationConfigError'; }
}

function computeDestinationTargets(
  opts: ApplyOptions,
  candidate: RuleCandidatePayload,
  slug: string,
  projectRoot: string,
  home: string
): DestinationTargets {
  if (opts.destination === 'corrections-md') {
    const t = correctionsMdTargets(slug, projectRoot, home);
    return { primary: t.feedbackMd, paths: [t.correctionsMd, t.feedbackMd] };
  }
  if (opts.destination === 'pattern-scanner') {
    if (opts.patternScannerCheckNumber == null) {
      throw new DestinationConfigError('pattern-scanner destination requires patternScannerCheckNumber');
    }
    const scannerPath = join(projectRoot, 'scripts', 'massu-pattern-scanner.sh');
    const driftGuardPath = join(projectRoot, 'packages', 'core', 'src', '__tests__', `${slug}-drift-guard.test.ts`);
    return { primary: scannerPath, paths: [scannerPath, driftGuardPath] };
  }
  if (opts.destination === 'claude-md-cr') {
    if (opts.claudeMdCrNumber == null) {
      throw new DestinationConfigError('claude-md-cr destination requires claudeMdCrNumber');
    }
    const claudePath = join(projectRoot, '.claude', 'CLAUDE.md');
    return { primary: claudePath, paths: [claudePath] };
  }
  if (opts.destination === 'custom-destination') {
    if (!opts.customDestination) {
      throw new DestinationConfigError('custom-destination requires customDestination config entry');
    }
    const raw = opts.customDestination.path;
    const absolute = isAbsolute(raw) ? raw : join(projectRoot, raw);
    // B-02/F-05 — ONE containment implementation, two anchors.
    //
    // This was a second, hand-rolled copy of the symlink-aware containment check.
    // Two copies of a containment check is how a containment check ends up
    // containing nothing: the renderer needs the SAME check anchored on the memory
    // dir (which lives under $HOME, outside projectRoot by construction), and a
    // verbatim reuse of this projectRoot-anchored copy would have rejected every
    // legitimate memory path. Both callers now share `lib/safe-write.ts`, which
    // additionally rejects NUL bytes and Windows reserved device names — neither of
    // which this copy checked.
    //
    // `allowNested` because a custom destination is legitimately a nested repo path
    // (`docs/brand-voice.md`); the memory dir is flat and uses the strict default.
    try {
      assertContainedIn(projectRoot, absolute, { allowNested: true });
    } catch (err) {
      throw new DestinationConfigError(
        `custom destination path escapes project root: ${raw} (${(err as Error).message})`
      );
    }
    return { primary: absolute, paths: [absolute] };
  }
  throw new DestinationConfigError(`unknown destination "${opts.destination}"`);
}

function writeDestination(
  opts: ApplyOptions,
  candidate: RuleCandidatePayload,
  slug: string,
  targets: DestinationTargets,
  auditRowId: number
): void {
  if (opts.destination === 'corrections-md') {
    return writeCorrectionsMd(opts, candidate, slug, targets, auditRowId);
  }
  if (opts.destination === 'pattern-scanner') {
    return writePatternScanner(opts, candidate, slug, targets);
  }
  if (opts.destination === 'claude-md-cr') {
    return writeClaudeMdCr(opts, candidate, slug, targets);
  }
  if (opts.destination === 'custom-destination') {
    return writeCustomDestination(opts, candidate, slug, targets);
  }
  throw new DestinationConfigError(`unknown destination "${opts.destination}"`);
}

function writeCorrectionsMd(
  opts: ApplyOptions,
  candidate: RuleCandidatePayload,
  slug: string,
  targets: DestinationTargets,
  auditRowId: number
): void {
  const [correctionsMd, feedbackMd] = targets.paths;
  const dateIso = new Date().toISOString().slice(0, 10);
  // A-09 — ONE format, shared with the reader (session-start) and the other writer
  // (knowledge-tools). This used to emit `## date: slug` while the reader parsed a
  // 4-column TABLE, so every rule it wrote was invisible to the injection that exists
  // to surface them. The provenance bullets are preserved as `extra`.
  const correctionsEntry = formatCorrectionEntry({
    date: dateIso,
    title: slug,
    rule: opts.draftText,
    extra: {
      prompt_hash: candidate.prompt_hash,
      score: candidate.score,
      audit_log_id: auditRowId,
    },
  });
  if (!existsSync(dirname(correctionsMd))) mkdirSync(dirname(correctionsMd), { recursive: true });
  const correctionsPre = existsSync(correctionsMd) ? readFileSync(correctionsMd, 'utf-8') : '# Corrections\n';
  writeFileSync(correctionsMd, correctionsPre + correctionsEntry, 'utf-8');

  // B-16 — THE APPLIER IS THE THIRD WRITER, AND IT NOW USES THE RENDERER'S CONVENTION.
  //
  // Left alone, this write had NO authorship credential — so post-B-01 every file the
  // applier ever wrote would be classified HUMAN forever and the renderer could never
  // maintain it: two Massu subsystems, two incompatible conventions, one of them
  // permanently frozen. Stamping it here is the structural answer, not a carve-out.
  //
  // The MAC covers the BODY only (a MAC cannot cover itself), exactly as in the renderer.
  const body = `${opts.draftText}\n`;
  const mac = mintAuthorship(body);
  const feedbackBody = [
    '---',
    `name: ${slug}`,
    `description: ${candidate.prompt.replace(/\n+/g, ' ').slice(0, 200)}`,
    'type: feedback',
    'metadata:',
    `  source: interactive`,
    `  prompt_hash: ${candidate.prompt_hash}`,
    `  audit_log_id: ${auditRowId}`,
    `  score: ${candidate.score}`,
    // Display-only; never read for trust (drift-guarded). The MAC is the credential.
    ...(mac ? ['massu_authored: true', `${RENDER_MAC_KEY}: ${mac}`] : []),
    '---',
    '',
    body,
  ].join('\n');
  // Atomic (A-14): a truncating writeFileSync leaves the file HALF-WRITTEN on ENOSPC or
  // a crash — in the operator's git-tracked memory directory.
  atomicWriteFileSync(feedbackMd, feedbackBody);
}

function writePatternScanner(
  opts: ApplyOptions,
  candidate: RuleCandidatePayload,
  slug: string,
  targets: DestinationTargets
): void {
  const [scannerPath, driftGuardPath] = targets.paths;
  const checkNumber = opts.patternScannerCheckNumber!;

  // Conflict detection: refuse if the exact prompt_hash is already
  // documented in the scanner (the auto-generated marker comments
  // include the hash).
  const scannerPre = existsSync(scannerPath) ? readFileSync(scannerPath, 'utf-8') : '';
  if (scannerPre.includes(`${SCANNER_AUTOGEN_MARKER_PREFIX} ${candidate.prompt_hash}`)) {
    throw new DestinationConfigError(
      `scanner already contains a check auto-generated for prompt_hash ${candidate.prompt_hash}`
    );
  }

  const checkBlock = [
    '',
    `${SCANNER_AUTOGEN_MARKER_PREFIX} ${candidate.prompt_hash} (slug=${slug})`,
    `# Check ${checkNumber}: ${slug}`,
    'echo ""',
    `echo "Check ${checkNumber}: ${slug}"`,
    opts.draftText.trim(),
    '',
  ].join('\n');
  writeFileSync(scannerPath, scannerPre + checkBlock, 'utf-8');

  // Sidecar drift-guard test — minimal stub that asserts the new check
  // exists in the scanner. Replaces hand-rolled drift-guard authoring
  // with a templated default the operator can elaborate later.
  const driftGuard = [
    '// Copyright (c) 2026 Massu. All rights reserved.',
    '// Licensed under BSL 1.1 - see LICENSE file for details.',
    '',
    `// Drift-guard mirror for pattern-scanner Check ${checkNumber} (${slug}).`,
    `// Auto-generated by /massu-rule approve for prompt_hash ${candidate.prompt_hash}.`,
    '',
    "import { describe, it, expect } from 'vitest';",
    "import { readFileSync } from 'fs';",
    "import { join } from 'path';",
    '',
    `describe('${slug} drift-guard', () => {`,
    `  it('pattern-scanner Check ${checkNumber} is present', () => {`,
    `    const scanner = readFileSync(join(process.cwd(), 'scripts', 'massu-pattern-scanner.sh'), 'utf-8');`,
    `    expect(scanner).toContain('Check ${checkNumber}: ${slug}');`,
    `    expect(scanner).toContain('${candidate.prompt_hash}');`,
    `  });`,
    `});`,
    '',
  ].join('\n');
  if (!existsSync(dirname(driftGuardPath))) mkdirSync(dirname(driftGuardPath), { recursive: true });
  writeFileSync(driftGuardPath, driftGuard, 'utf-8');
}

function writeClaudeMdCr(
  opts: ApplyOptions,
  candidate: RuleCandidatePayload,
  slug: string,
  targets: DestinationTargets
): void {
  const [claudePath] = targets.paths;
  const crNumber = opts.claudeMdCrNumber!;
  const pre = existsSync(claudePath) ? readFileSync(claudePath, 'utf-8') : '';

  // Conflict detection: refuse if a CR-<N> entry already exists.
  if (new RegExp(`\\bCR-${crNumber}\\b`).test(pre)) {
    throw new DestinationConfigError(`CLAUDE.md already contains a CR-${crNumber} entry`);
  }

  // ARCH-01 fix: splice the table row in addition to appending the body
  // block. CR-46 #3 forbids piecemeal escape hatches — the slash command
  // is the SOLE authoring surface, so it must write both the table row
  // AND the body section in one atomic action.
  const tableHeaderRe = /(\| ID \| Rule \| Verification Type \|\s*\n\|[-| ]+\|\s*\n)((?:\| CR-\d+ \|[^\n]*\n)+)/;
  const tableMatch = pre.match(tableHeaderRe);
  if (!tableMatch) {
    throw new DestinationConfigError(
      'CLAUDE.md does not contain a recognizable Canonical Rules table — refusing to write CR row'
    );
  }
  const tableHeader = tableMatch[1];
  const existingRows = tableMatch[2];
  const newRow = `| CR-${crNumber} | ${opts.draftText.replace(/\n+/g, ' ').trim().slice(0, 400)} | VR-NEW-${slug.toUpperCase()} |\n`;
  const updatedTable = tableHeader + existingRows + newRow;
  const afterTable = pre.replace(tableHeaderRe, updatedTable);

  // Append the body section after the table replacement.
  const block = [
    '',
    '---',
    '',
    `### CR-${crNumber}: ${slug}`,
    '',
    `Auto-promoted from rule-candidate ${candidate.prompt_hash} (score=${candidate.score}).`,
    '',
    opts.draftText,
    '',
  ].join('\n');
  writeFileSync(claudePath, afterTable + block, 'utf-8');
}

function writeCustomDestination(
  opts: ApplyOptions,
  candidate: RuleCandidatePayload,
  slug: string,
  targets: DestinationTargets
): void {
  const [destPath] = targets.paths;
  const entry = opts.customDestination!;
  const vars: TemplateVars = {
    date: new Date().toISOString(),
    slug,
    score: candidate.score,
    signals_csv: candidate.signals.map(s => s.name).join(','),
    prompt_preview: candidate.prompt.replace(/\n+/g, ' ').slice(0, 120),
    destination_name: entry.name,
  };
  const rendered = renderTemplate(entry.template, vars);
  if (!existsSync(dirname(destPath))) mkdirSync(dirname(destPath), { recursive: true });
  const pre = existsSync(destPath) ? readFileSync(destPath, 'utf-8') : '';
  const sep = pre && !pre.endsWith('\n') ? '\n' : '';
  writeFileSync(destPath, pre + sep + rendered + (rendered.endsWith('\n') ? '' : '\n'), 'utf-8');
}

// ============================================================
// ARCH-02 fix: dismiss() write path
// ============================================================

export interface DismissOptions {
  candidateId: string;
  reason: string;
  projectRoot?: string;
}

export interface DismissResult {
  ok: boolean;
  audit_log_id?: number;
  signals_blacklisted_or_incremented: number;
  error?: string;
}

/**
 * Dismiss a rule candidate. Plan §6 row 2 dismissal-loop write path.
 *
 * Steps:
 *   1. Validate candidate id; read sidecar.
 *   2. UPSERT each signal that fired on the dismissed prompt into
 *      `prompt_outcomes_signal_blacklist` (dismissal_count += 1).
 *      Hits ≥5 → signal contributes 0 points permanently (handled by
 *      `rule-candidate-detector.applyDismissal`).
 *   3. INSERT `audit_log (event_type='rule_dismissed', metadata={...})`.
 *   4. Append `{id, prompt_hash, score, signals_fired, reason, timestamp}`
 *      to `.massu/rule-candidates/.dismissed.jsonl`.
 *   5. Delete the candidate sidecar.
 *
 * Wraps SQL writes in a single transaction so the audit row + blacklist
 * upserts are all-or-nothing.
 */
export function dismissRuleCandidate(
  db: Database.Database,
  opts: DismissOptions
): DismissResult {
  if (!CANDIDATE_ID_PATTERN.test(opts.candidateId)) {
    throw new InvalidCandidateIdError(opts.candidateId);
  }
  const projectRoot = opts.projectRoot ?? getProjectRoot();
  const candidate = readCandidate(opts.candidateId, projectRoot);
  const candidatePath = join(projectRoot, '.massu', 'rule-candidates', `${opts.candidateId}.json`);

  db.exec('BEGIN');
  let auditRowId: number | undefined;
  let blacklistUpdates = 0;
  try {
    const upsert = db.prepare(`
      INSERT INTO prompt_outcomes_signal_blacklist (signal, dismissal_count, last_dismissed_at)
      VALUES (?, 1, datetime('now'))
      ON CONFLICT(signal) DO UPDATE SET
        dismissal_count = dismissal_count + 1,
        last_dismissed_at = datetime('now')
    `);
    for (const sig of candidate.signals) {
      // Downweight only the POSITIVE signals — exclusions (slash_command,
      // dismissal) carry negative base weights and aren't candidates for
      // further downweighting (they already returned -100 at detect time).
      if (sig.baseWeight <= 0) continue;
      const r = upsert.run(sig.name);
      blacklistUpdates += r.changes;
    }

    const entry: AuditEntry = {
      eventType: 'rule_dismissed',
      actor: 'human',
      sessionId: candidate.session_id,
      metadata: {
        candidate_id: opts.candidateId,
        prompt_hash: candidate.prompt_hash,
        score: candidate.score,
        reason: opts.reason,
        signals_fired: candidate.signals.map(s => s.name),
      },
    };
    logAuditEntry(db, entry);
    auditRowId = (db.prepare('SELECT last_insert_rowid() AS id').get() as { id: number }).id;

    db.exec('COMMIT');
  } catch (err) {
    db.exec('ROLLBACK');
    return {
      ok: false,
      signals_blacklisted_or_incremented: 0,
      error: err instanceof Error ? err.message : String(err),
    };
  }

  // File-side compensating actions (post-commit; failures are best-effort
  // and surface via the failure log).
  try {
    const dismissedLog = join(projectRoot, '.massu', 'rule-candidates', '.dismissed.jsonl');
    if (!existsSync(dirname(dismissedLog))) mkdirSync(dirname(dismissedLog), { recursive: true });
    const pre = existsSync(dismissedLog) ? readFileSync(dismissedLog, 'utf-8') : '';
    const sep = pre && !pre.endsWith('\n') ? '\n' : '';
    writeFileSync(dismissedLog, pre + sep + JSON.stringify({
      id: opts.candidateId,
      prompt_hash: candidate.prompt_hash,
      score: candidate.score,
      signals_fired: candidate.signals.map(s => s.name),
      reason: opts.reason,
      audit_log_id: auditRowId,
      timestamp: new Date().toISOString(),
    }) + '\n', 'utf-8');
    if (existsSync(candidatePath)) unlinkSync(candidatePath);
  } catch (err) {
    appendFailureLog(projectRoot, {
      candidate_id: opts.candidateId,
      destination: 'dismiss-postcommit',
      error: err instanceof Error ? err.message : String(err),
      timestamp: new Date().toISOString(),
    });
  }

  // P1-002: capture the DISMISSED funnel event (Team-gated inside the helper).
  recordDismissalFunnelEvent(db, candidate.prompt_hash, candidate.score);
  return {
    ok: true,
    audit_log_id: auditRowId,
    signals_blacklisted_or_incremented: blacklistUpdates,
  };
}

function appendFailureLog(projectRoot: string, entry: Record<string, unknown>): void {
  try {
    const dir = join(projectRoot, '.massu', 'rule-candidates');
    if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
    const logPath = join(dir, '.failures.jsonl');
    const pre = existsSync(logPath) ? readFileSync(logPath, 'utf-8') : '';
    const sep = pre && !pre.endsWith('\n') ? '\n' : '';
    writeFileSync(logPath, pre + sep + JSON.stringify(entry) + '\n', 'utf-8');
  } catch {
    // Best-effort
  }
}
