// Copyright (c) 2026 Massu. All rights reserved.
// Licensed under BSL 1.1 - see LICENSE file for details.

/**
 * P-002 drift-guard test: `.mcp.json` generated by `registerMcpServer`
 * MUST pin the `@massu/core` version, never write the bare unpinned form.
 *
 * The structural class this closes: unpinned `npx -y @massu/core` resolves
 * to the latest dist-tag on every spawn, silently drifting customer setups
 * across versions and bypassing operator-attended release ceremonies.
 *
 * MEMORY precedent: `feedback_mcp_pin_version_in_mcp_json` (1.6.2; commit 0b60916).
 */

import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { existsSync, mkdtempSync, readFileSync, rmSync } from 'fs';
import { resolve } from 'path';
import { tmpdir } from 'os';
import { registerMcpServer } from '../commands/init.ts';

let fixtureDir: string;

beforeEach(() => {
  fixtureDir = mkdtempSync(resolve(tmpdir(), 'massu-mcp-pin-'));
});

afterEach(() => {
  if (existsSync(fixtureDir)) {
    rmSync(fixtureDir, { recursive: true, force: true });
  }
});

describe('P-002: .mcp.json version pinning', () => {
  it('writes a pinned @massu/core@X.Y.Z reference', () => {
    const registered = registerMcpServer(fixtureDir);
    expect(registered).toBe(true);

    const mcpPath = resolve(fixtureDir, '.mcp.json');
    expect(existsSync(mcpPath)).toBe(true);

    const content = readFileSync(mcpPath, 'utf-8');

    // Must contain a pinned reference.
    expect(content).toMatch(/@massu\/core@\d+\.\d+\.\d+/);

    // Must NOT contain the bare unpinned form (regression guard).
    // Specifically: the args array must NOT have a bare "@massu/core" entry.
    const parsed = JSON.parse(content);
    const args = parsed.mcpServers.massu.args as string[];
    expect(args).toHaveLength(2);
    expect(args[0]).toBe('-y');
    expect(args[1]).not.toBe('@massu/core');
    expect(args[1]).toMatch(/^@massu\/core@\d+\.\d+\.\d+/);
  });

  it('uses the installer\'s own version (matches package.json)', () => {
    registerMcpServer(fixtureDir);

    // Read installer's own version.
    const pkgPath = resolve(__dirname, '../../package.json');
    expect(existsSync(pkgPath)).toBe(true);
    const pkg = JSON.parse(readFileSync(pkgPath, 'utf-8'));
    expect(pkg.name).toBe('@massu/core');
    expect(typeof pkg.version).toBe('string');

    const mcpPath = resolve(fixtureDir, '.mcp.json');
    const content = JSON.parse(readFileSync(mcpPath, 'utf-8'));
    const args = content.mcpServers.massu.args as string[];

    expect(args[1]).toBe(`@massu/core@${pkg.version}`);
  });
});
