// Copyright (c) 2026 Massu. All rights reserved.
// Licensed under BSL 1.1 - see LICENSE file for details.

/**
 * P-002 drift-guard test: `.mcp.json` generated by `registerMcpServer`
 * MUST pin the `@massu/core` version, never write the bare unpinned form.
 *
 * The structural class this closes: unpinned `npx -y @massu/core` resolves
 * to the latest dist-tag on every spawn, silently drifting customer setups
 * across versions and bypassing operator-attended release ceremonies.
 *
 * MEMORY precedent: `feedback_mcp_pin_version_in_mcp_json` (1.6.2; commit 0b60916).
 */

import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { existsSync, mkdtempSync, readFileSync, rmSync } from 'fs';
import { resolve } from 'path';
import { tmpdir } from 'os';
import { registerMcpServer } from '../commands/init.ts';

let fixtureDir: string;

beforeEach(() => {
  fixtureDir = mkdtempSync(resolve(tmpdir(), 'massu-mcp-pin-'));
});

afterEach(() => {
  if (existsSync(fixtureDir)) {
    rmSync(fixtureDir, { recursive: true, force: true });
  }
});

describe('P-002: .mcp.json version pinning', () => {
  it('writes a pinned @massu/core@X.Y.Z reference', () => {
    const registered = registerMcpServer(fixtureDir);
    expect(registered).toBe(true);

    const mcpPath = resolve(fixtureDir, '.mcp.json');
    expect(existsSync(mcpPath)).toBe(true);

    const content = readFileSync(mcpPath, 'utf-8');

    // Must PIN A VERSION. AMENDED (plan-2026-08-01 phase B): massu emits either the npx
    // form (`-y @massu/core@X.Y.Z`) or the version-stable shim form (args `[X.Y.Z]`). The
    // property P-002 protects is "no drift onto an unpinned @massu/core", and BOTH forms
    // satisfy it. The old assertion pinned the npx MECHANISM instead (G28).
    const parsed = JSON.parse(content);
    const args = parsed.mcpServers.massu.args as string[];
    if (args[0] === '-y') {
      expect(args).toHaveLength(2);
      expect(args[1]).not.toBe('@massu/core');           // the bare unpinned form
      expect(args[1]).toMatch(/^@massu\/core@\d+\.\d+\.\d+/);
      expect(content).toMatch(/@massu\/core@\d+\.\d+\.\d+/);
    } else {
      expect(args).toHaveLength(1);
      expect(args[0]).toMatch(/^\d+\.\d+\.\d+/);      // an explicit pinned version
      expect(content).not.toContain('"@massu/core"');     // never the bare unpinned form
    }
  });

  it('uses the installer\'s own version (matches package.json)', () => {
    registerMcpServer(fixtureDir);

    // Read installer's own version.
    const pkgPath = resolve(__dirname, '../../package.json');
    expect(existsSync(pkgPath)).toBe(true);
    const pkg = JSON.parse(readFileSync(pkgPath, 'utf-8'));
    expect(pkg.name).toBe('@massu/core');
    expect(typeof pkg.version).toBe('string');

    const mcpPath = resolve(fixtureDir, '.mcp.json');
    const content = JSON.parse(readFileSync(mcpPath, 'utf-8'));
    const args = content.mcpServers.massu.args as string[];

    // AMENDED (plan-2026-08-01 phase B): the shim form carries the version as args[0].
    // Either way the emitted server MUST name the installer's own version.
    if (args[0] === '-y') expect(args[1]).toBe(`@massu/core@${pkg.version}`);
    else expect(args[0]).toBe(pkg.version);
  });
});
