// Copyright (c) 2026 Massu. All rights reserved.
// Licensed under BSL 1.1 - see LICENSE file for details.

/**
 * P-003 drift-guard test: `.claude/settings.local.json` generated by
 * `installHooks` MUST NOT contain absolute filesystem paths in hook
 * commands. Any absolute path (especially npx-cache paths like
 * `/opt/homebrew/lib/node_modules/...`) is invalidated by cache clears,
 * global-install relocations, or npx upgrades — silently 404-ing every
 * hook and breaking auto-learning without any visible signal to the customer.
 *
 * The fix (1.9.4): hooks are invoked via `npx -y @massu/core@<version>
 * hook-runner <name>` so the hook file is resolved dynamically at fire-time.
 */

import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { existsSync, mkdtempSync, readFileSync, rmSync } from 'fs';
import { resolve } from 'path';
import { tmpdir } from 'os';
import { installHooks, buildHooksConfig } from '../commands/init.ts';

let fixtureDir: string;

beforeEach(() => {
  fixtureDir = mkdtempSync(resolve(tmpdir(), 'massu-hook-paths-'));
});

afterEach(() => {
  if (existsSync(fixtureDir)) {
    rmSync(fixtureDir, { recursive: true, force: true });
  }
});

/**
 * Forbidden absolute-path prefixes that have caused real install drift.
 * Empty `/Users/` catch-all is intentional — even non-Homebrew paths
 * are problematic if baked.
 */
const FORBIDDEN_PATH_PREFIXES = [
  '/opt/homebrew',
  '/usr/local/lib/node_modules',
  '/usr/local/bin',
  // Bare `/Users/` is too broad on macOS dev hosts (matches legitimate
  // user-owned project roots), so only flag node_modules sub-paths under it.
];

/**
 * Substring guards — these forbidden literals must never appear ANYWHERE
 * inside hook command strings. Wider than prefix matching for defense-in-depth.
 */
const FORBIDDEN_PATH_SUBSTRINGS = [
  '/opt/homebrew/lib/node_modules',
  '/usr/local/lib/node_modules',
  // npx cache root variants seen in the wild.
  '/.npm/_npx/',
  '/.nvm/versions/node/',
];

function assertNoAbsolutePaths(command: string): void {
  for (const sub of FORBIDDEN_PATH_SUBSTRINGS) {
    expect(command).not.toContain(sub);
  }
  for (const prefix of FORBIDDEN_PATH_PREFIXES) {
    // Tokenize on spaces — flag if any token starts with a forbidden absolute prefix.
    for (const token of command.split(/\s+/)) {
      expect(token.startsWith(prefix)).toBe(false);
    }
  }
}

describe('P-003: hook commands contain no absolute paths', () => {
  it('buildHooksConfig output has no forbidden absolute paths', () => {
    const hooksConfig = buildHooksConfig();
    for (const event of Object.keys(hooksConfig)) {
      for (const group of hooksConfig[event]) {
        for (const entry of group.hooks) {
          assertNoAbsolutePaths(entry.command);
        }
      }
    }
  });

  it('installHooks writes settings.local.json with no forbidden absolute paths', () => {
    installHooks(fixtureDir);
    const settingsPath = resolve(fixtureDir, '.claude/settings.local.json');
    expect(existsSync(settingsPath)).toBe(true);
    const raw = readFileSync(settingsPath, 'utf-8');

    // Whole-file substring check is the strongest form of this guard —
    // even if a hook command line is restructured, forbidden literals
    // (npx cache prefixes, Homebrew paths) must NEVER appear on disk.
    for (const sub of FORBIDDEN_PATH_SUBSTRINGS) {
      expect(raw).not.toContain(sub);
    }
  });

  it('all hook commands use the hook-runner subcommand (dynamic resolution)', () => {
    const hooksConfig = buildHooksConfig();
    for (const event of Object.keys(hooksConfig)) {
      for (const group of hooksConfig[event]) {
        for (const entry of group.hooks) {
          // Every Massu canonical command must use `hook-runner` so the hook
          // file is resolved at fire-time rather than at install-time.
          expect(entry.command).toContain('hook-runner ');
          // And must include the pinned-version reference (P-002 coupling).
          expect(entry.command).toMatch(/@massu\/core@\d+\.\d+\.\d+/);
        }
      }
    }
  });
});
