// Copyright (c) 2026 Massu. All rights reserved.
// Licensed under BSL 1.1 - see LICENSE file for details.

/**
 * P-003 drift-guard test: `.claude/settings.local.json` generated by
 * `installHooks` MUST NOT contain absolute filesystem paths in hook
 * commands. Any absolute path (especially npx-cache paths like
 * `/opt/homebrew/lib/node_modules/...`) is invalidated by cache clears,
 * global-install relocations, or npx upgrades — silently 404-ing every
 * hook and breaking auto-learning without any visible signal to the customer.
 *
 * The fix (1.9.4): hooks are invoked via `npx -y @massu/core@<version>
 * hook-runner <name>` so the hook file is resolved dynamically at fire-time.
 */

import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { existsSync, mkdtempSync, readFileSync, rmSync } from 'fs';
import { resolve } from 'path';
import { tmpdir } from 'os';
import { installHooks, buildHooksConfig } from '../commands/init.ts';

let fixtureDir: string;

beforeEach(() => {
  fixtureDir = mkdtempSync(resolve(tmpdir(), 'massu-hook-paths-'));
});

afterEach(() => {
  if (existsSync(fixtureDir)) {
    rmSync(fixtureDir, { recursive: true, force: true });
  }
});

/**
 * Forbidden absolute-path prefixes that have caused real install drift.
 * Empty `/Users/` catch-all is intentional — even non-Homebrew paths
 * are problematic if baked.
 */
const FORBIDDEN_PATH_PREFIXES = [
  '/opt/homebrew',
  '/usr/local/lib/node_modules',
  '/usr/local/bin',
  // Bare `/Users/` is too broad on macOS dev hosts (matches legitimate
  // user-owned project roots), so only flag node_modules sub-paths under it.
];

/**
 * Substring guards — these forbidden literals must never appear ANYWHERE
 * inside hook command strings. Wider than prefix matching for defense-in-depth.
 */
const FORBIDDEN_PATH_SUBSTRINGS = [
  '/opt/homebrew/lib/node_modules',
  '/usr/local/lib/node_modules',
  // npx cache root variants seen in the wild.
  '/.npm/_npx/',
  '/.nvm/versions/node/',
];

function assertNoAbsolutePaths(command: string): void {
  for (const sub of FORBIDDEN_PATH_SUBSTRINGS) {
    expect(command).not.toContain(sub);
  }
  for (const prefix of FORBIDDEN_PATH_PREFIXES) {
    // Tokenize on spaces — flag if any token starts with a forbidden absolute prefix.
    for (const token of command.split(/\s+/)) {
      expect(token.startsWith(prefix)).toBe(false);
    }
  }
}

/**
 * BOTH command forms, always — never whichever one this machine happens to produce.
 *
 * `buildHooksConfig()` used to resolve the shim internally, so the shape it emitted was a
 * function of ambient machine state: a developer with `~/.massu/bin/massu-hook` present got
 * the shim form and NEVER exercised the npx form, and vice versa. That is not a style
 * problem — it made this guard DECORATION. The anti-vacuity plant targets the npx branch of
 * `hookCmd`; on any machine with a live shim that branch is never evaluated, the planted
 * absolute path never reaches a command, and the guard stayed GREEN with the defect
 * installed (measured by the 2026-08-11 sweep: "stayed GREEN with the defect planted +
 * ORACLE-confirmed. IT IS DECORATION.").
 *
 * Worse, the shim's presence was itself caused by the test suite — `massu-shim-drift-guard`
 * installed one into the real `$HOME` on every run — so the guard disarmed itself.
 *
 * Enumerating both forms makes the property hold regardless of what is installed, and makes
 * a plant on EITHER branch fire (G18 — the candidate set IS the gate; G27 — assert the
 * property, not a correlate of it).
 */
const SHIM_FORMS: Array<{ label: string; shim: string | null }> = [
  { label: 'npx form (no shim installed)', shim: null },
  { label: 'shim form (shim installed)', shim: '/tmp/massu-test-shim/massu-hook' },
];

describe('P-003: hook commands contain no absolute paths', () => {
  for (const { label, shim } of SHIM_FORMS) {
    it(`buildHooksConfig output has no forbidden absolute paths — ${label}`, () => {
      const hooksConfig = buildHooksConfig(undefined, shim);

      // M1 — prove it looked. A zero-command config would satisfy every assertion below.
      let commands = 0;
      for (const event of Object.keys(hooksConfig)) {
        for (const group of hooksConfig[event]) {
          for (const entry of group.hooks) {
            commands++;
            assertNoAbsolutePaths(entry.command);
          }
        }
      }
      expect(commands, 'buildHooksConfig emitted NO commands — this check is vacuous').toBeGreaterThan(0);
    });
  }

  it('buildHooksConfig output has no forbidden absolute paths (ambient machine state)', () => {
    const hooksConfig = buildHooksConfig();
    let commands = 0;
    for (const event of Object.keys(hooksConfig)) {
      for (const group of hooksConfig[event]) {
        for (const entry of group.hooks) {
          commands++;
          assertNoAbsolutePaths(entry.command);
        }
      }
    }
    expect(commands, 'buildHooksConfig emitted NO commands — this check is vacuous').toBeGreaterThan(0);
  });

  it('installHooks writes settings.local.json with no forbidden absolute paths', () => {
    installHooks(fixtureDir);
    const settingsPath = resolve(fixtureDir, '.claude/settings.local.json');
    expect(existsSync(settingsPath)).toBe(true);
    const raw = readFileSync(settingsPath, 'utf-8');

    // Whole-file substring check is the strongest form of this guard —
    // even if a hook command line is restructured, forbidden literals
    // (npx cache prefixes, Homebrew paths) must NEVER appear on disk.
    for (const sub of FORBIDDEN_PATH_SUBSTRINGS) {
      expect(raw).not.toContain(sub);
    }
  });

  // Parametrised over BOTH forms for the same reason as the absolute-path checks above:
  // an assertion that only ever sees the shape this machine happens to emit cannot be
  // relied on to fail when the OTHER shape regresses.
  it.each(SHIM_FORMS)('all hook commands use the hook-runner subcommand — $label', ({ shim }) => {
    const hooksConfig = buildHooksConfig(undefined, shim);
    let commands = 0;
    for (const event of Object.keys(hooksConfig)) {
      for (const group of hooksConfig[event]) {
        for (const entry of group.hooks) {
          commands++;
          // Every Massu canonical command must use `hook-runner` so the hook
          // file is resolved at fire-time rather than at install-time.
          expect(entry.command).toContain('hook-runner ');
          // And must PIN A VISIBLE VERSION (P-002 coupling).
          //
          // AMENDED by plan-2026-08-01 phase B. This asserted the literal `@massu/core@X.Y.Z`,
          // which is the npx form's CORRELATE of the property, not the property itself (G28).
          // The shim form `"<shim>" X.Y.Z hook-runner <name>` pins the version just as visibly
          // — the command still states in plain sight which massu version this repo runs — so
          // the assertion now tests THAT.
          //
          // P-003's substrate rule is UNCHANGED and still enforced by assertNoAbsolutePaths
          // above. The shim path is deliberately not in the forbidden set because it is
          // version-STABLE (a bump cannot invalidate it), rewritten on every `install-hooks`,
          // and falls back to npx at FIRE time when the runtime is absent — so it cannot
          // silently 404 the way `/.npm/_npx/<hash>/` could. Those volatile locations remain
          // forbidden.
          expect(
            entry.command,
            'hook command pins no visible version in either the npx or the shim form',
          ).toMatch(/(@massu\/core@\d+\.\d+\.\d+|massu-hook"?\s+\d+\.\d+\.\d+)/);
        }
      }
    }
    expect(commands, 'buildHooksConfig emitted NO commands — this check is vacuous').toBeGreaterThan(0);
  });
});
