// Copyright (c) 2026 Massu. All rights reserved.
// Licensed under BSL 1.1 - see LICENSE file for details.

// plan-v0.2-interactive-rule-approval P-D-007: drift-guard mirror of
// pattern-scanner Check 29. Per CR-52 three-layer pattern (scanner +
// vitest + protocol), every scanner check that enforces a class of bug
// also ships an AST-aware vitest assertion so post-commit CI catches
// what pre-commit scanner might miss when the markers are mangled by
// merge conflicts or hand-edits.

import { describe, it, expect } from 'vitest';
import { readFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

function resolveScannerPath(): string {
  // Anchor on this test file's own location (cwd-independent).
  return join(__dirname, '..', '..', '..', '..', 'scripts', 'massu-pattern-scanner.sh');
}

describe('pattern-scanner Check 29 drift-guard (P-D-007)', () => {
  it('every auto-generated marker is followed by a `# Check N:` line within 4 lines', () => {
    const scanner = readFileSync(resolveScannerPath(), 'utf-8');
    const lines = scanner.split('\n');
    const markerRe = /^# auto-generated by \/massu-rule approve [a-f0-9]+ \(slug=[\w.-]+\)/;
    const checkRe = /^# Check \d+:/;
    const violations: number[] = [];

    for (let i = 0; i < lines.length; i++) {
      if (markerRe.test(lines[i])) {
        const next = lines.slice(i + 1, i + 5);
        if (!next.some(l => checkRe.test(l))) {
          violations.push(i + 1); // 1-indexed line number for error reporting
        }
      }
    }

    expect(violations).toEqual([]);
  });

  it('Check 29 itself is present in the scanner', () => {
    const scanner = readFileSync(resolveScannerPath(), 'utf-8');
    expect(scanner).toContain('Check 29: Auto-generated scanner additions');
    expect(scanner).toContain('P-D-006');
  });

  it('auto-generated marker shape rejects malformed prompt_hash (sanity)', () => {
    // The regex must require a hex hash and a slug; this test ensures the
    // regex itself doesn't accidentally match a bare comment like
    // `# auto-generated by other-tool`.
    const markerRe = /^# auto-generated by \/massu-rule approve [a-f0-9]+ \(slug=[\w.-]+\)/;
    expect(markerRe.test('# auto-generated by /massu-rule approve abc123 (slug=foo_bar)')).toBe(true);
    expect(markerRe.test('# auto-generated by other-tool')).toBe(false);
    expect(markerRe.test('# auto-generated by /massu-rule approve')).toBe(false);
    expect(markerRe.test('# auto-generated by /massu-rule approve abc123')).toBe(false);
  });
});
