// Copyright (c) 2026 Massu. All rights reserved.
// Licensed under BSL 1.1 - see LICENSE file for details.

// plan-v0.2-interactive-rule-approval P-D-005: extended applier tests.
// Happy paths for pattern-scanner, claude-md-cr, custom-destination +
// conflict-detection refusals + snapshot-set restore for each class.

import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, existsSync, rmSync } from 'fs';
import { join } from 'path';
import { tmpdir } from 'os';
import Database from 'better-sqlite3';
import { initMemorySchema } from '../memory-db.ts';
import {
  applyRuleCandidate,
  type RuleCandidatePayload,
} from '../rule-candidate-applier.ts';
import { encodeMemoryDirName } from '../lib/memory-path.ts';
import type { CustomDestinationConfig } from '../rule-classifier.ts';
import { _setCachedTierForTest, _resetCachedTier } from '../license.ts';

let tmpHome: string;
let tmpProjectRoot: string;
let db: Database.Database;

function setup(): void {
  tmpHome = mkdtempSync(join(tmpdir(), 'massu-applier-ext-home-'));
  tmpProjectRoot = mkdtempSync(join(tmpdir(), 'massu-applier-ext-proj-'));
  const memoryDir = join(tmpHome, '.claude', 'projects', encodeMemoryDirName(tmpProjectRoot), 'memory');
  mkdirSync(memoryDir, { recursive: true });
  writeFileSync(join(memoryDir, 'MEMORY.md'), '# Memory Index\n', 'utf-8');
  mkdirSync(join(tmpProjectRoot, '.massu', 'rule-candidates'), { recursive: true });
  // Scaffold the scanner script + CLAUDE.md targets so destination handlers
  // have something to read.
  mkdirSync(join(tmpProjectRoot, 'scripts'), { recursive: true });
  writeFileSync(join(tmpProjectRoot, 'scripts', 'massu-pattern-scanner.sh'), '#!/usr/bin/env bash\nset -euo pipefail\necho "existing scanner content"\n', 'utf-8');
  mkdirSync(join(tmpProjectRoot, '.claude'), { recursive: true });
  // ARCH-01 fix: writeClaudeMdCr requires a recognizable Canonical Rules
  // markdown table header + at least one CR-N row. Seed the fixture
  // accordingly.
  writeFileSync(join(tmpProjectRoot, '.claude', 'CLAUDE.md'),
    '# Existing CLAUDE.md\n\n## Canonical Rules\n\n| ID | Rule | Verification Type |\n|---|---|---|\n| CR-1 | first | VR-FIRST |\n| CR-2 | second | VR-SECOND |\n',
    'utf-8');
  mkdirSync(join(tmpProjectRoot, 'packages', 'core', 'src', '__tests__'), { recursive: true });
}

function teardown(): void {
  rmSync(tmpHome, { recursive: true, force: true });
  rmSync(tmpProjectRoot, { recursive: true, force: true });
}

function writeCandidate(payload: Partial<RuleCandidatePayload> = {}): string {
  const candidate: RuleCandidatePayload = {
    prompt: 'use getConfig() instead of direct yaml.load',
    prompt_hash: 'abc123def4567890',
    score: 90,
    signals: [
      { name: 'strong_correction_phrase', baseWeight: 40, applied: 40 },
      { name: 'prior_edit_or_write', baseWeight: 25, applied: 25 },
    ],
    prior_turn_files: ['packages/core/src/config-loader.ts'],
    timestamp: '2026-05-20T12:00:00Z',
    session_id: 'session-xyz',
    ...payload,
  };
  const path = join(tmpProjectRoot, '.massu', 'rule-candidates', `${candidate.prompt_hash}.json`);
  writeFileSync(path, JSON.stringify(candidate, null, 2), 'utf-8');
  return candidate.prompt_hash;
}

describe('rule-candidate-applier (extended destinations)', () => {
  beforeEach(() => {
    setup();
    // CR-54: applyRuleCandidate is tier-gated (Pro+). Seed Pro so promotion runs.
    _setCachedTierForTest('pro');
    db = new Database(':memory:');
    db.pragma('journal_mode = WAL');
    db.pragma('foreign_keys = ON');
    initMemorySchema(db);
    db.prepare(`INSERT INTO sessions (session_id, started_at, started_at_epoch) VALUES ('session-xyz', datetime('now'), 0)`).run();
  });

  afterEach(() => { _resetCachedTier(); db.close(); teardown(); });

  describe('pattern-scanner destination', () => {
    it('happy path: appends Check block + writes drift-guard sidecar', async () => {
      const id = writeCandidate();
      const result = await applyRuleCandidate(db, {
        candidateId: id,
        destination: 'pattern-scanner',
        draftText: 'grep -RnE "yaml\\.(load|parse)\\(readFileSync" packages/core/src/ && fail "use getConfig()"',
        slug: 'no_direct_yaml_load',
        patternScannerCheckNumber: 30,
        projectRoot: tmpProjectRoot,
        home: tmpHome,
      });
      expect(result.ok).toBe(true);

      const scanner = readFileSync(join(tmpProjectRoot, 'scripts', 'massu-pattern-scanner.sh'), 'utf-8');
      expect(scanner).toContain('Check 30: no_direct_yaml_load');
      expect(scanner).toContain('auto-generated by /massu-rule approve abc123def4567890');
      expect(scanner).toContain('yaml');

      const driftGuard = join(tmpProjectRoot, 'packages', 'core', 'src', '__tests__', 'no_direct_yaml_load-drift-guard.test.ts');
      expect(existsSync(driftGuard)).toBe(true);
      const driftContent = readFileSync(driftGuard, 'utf-8');
      expect(driftContent).toContain('Check 30: no_direct_yaml_load');
      expect(driftContent).toContain('abc123def4567890');
    });

    it('conflict-detection: refuses a second approve for same prompt_hash', async () => {
      const id = writeCandidate();
      await applyRuleCandidate(db, {
        candidateId: id, destination: 'pattern-scanner',
        draftText: 'grep -q foo packages/core/src/', slug: 'no_direct_yaml_load',
        patternScannerCheckNumber: 30, projectRoot: tmpProjectRoot, home: tmpHome,
      });
      writeCandidate();  // re-create the sidecar so the second call reaches Step 2
      const result = await applyRuleCandidate(db, {
        candidateId: id, destination: 'pattern-scanner',
        draftText: 'grep -q foo packages/core/src/', slug: 'no_direct_yaml_load',
        patternScannerCheckNumber: 31, projectRoot: tmpProjectRoot, home: tmpHome,
      });
      // First call set the UNIQUE INDEX lock → second call is idempotent_noop.
      expect(result.ok).toBe(true);
      expect(result.idempotent_noop).toBe(true);
    });

    it('snapshot-set: drift-guard sidecar deleted on rollback (NEW file)', async (ctx) => {
      const id = writeCandidate();
      // Pre-fill MEMORY.md as read-only to force a Step-3 failure.
      const memoryIndex = join(tmpHome, '.claude', 'projects', encodeMemoryDirName(tmpProjectRoot), 'memory', 'MEMORY.md');
      const { chmodSync, statSync } = require('fs');
      chmodSync(memoryIndex, 0o444);
      const writable = (statSync(memoryIndex).mode & 0o200) !== 0;
      // G-1 (plan-2026-07-26-anti-vacuity-9-unproven-gates): chmod is a no-op when running as root, so the Step-3 failure this
      // test needs cannot be forced. ctx.skip() reports SKIPPED; the old `return`
      // reported PASSED for a rollback that was never exercised.
      if (writable) { chmodSync(memoryIndex, 0o644); ctx.skip(); }

      try {
        const result = await applyRuleCandidate(db, {
          candidateId: id, destination: 'pattern-scanner',
          draftText: 'grep -q foo /', slug: 'snapshot_test',
          patternScannerCheckNumber: 50, projectRoot: tmpProjectRoot, home: tmpHome,
        });
        expect(result.ok).toBe(false);

        // Drift-guard sidecar (NEW file) should be unlinked
        const driftGuard = join(tmpProjectRoot, 'packages', 'core', 'src', '__tests__', 'snapshot_test-drift-guard.test.ts');
        expect(existsSync(driftGuard)).toBe(false);

        // Scanner restored to pre-write content
        const scanner = readFileSync(join(tmpProjectRoot, 'scripts', 'massu-pattern-scanner.sh'), 'utf-8');
        expect(scanner).not.toContain('snapshot_test');
      } finally {
        chmodSync(memoryIndex, 0o644);
      }
    });
  });

  describe('claude-md-cr destination', () => {
    it('happy path: appends CR-N body section', async () => {
      const id = writeCandidate();
      const result = await applyRuleCandidate(db, {
        candidateId: id, destination: 'claude-md-cr',
        draftText: 'Every approve must reference a plan token in the audit_log metadata.',
        slug: 'audit_log_plan_token', claudeMdCrNumber: 99,
        projectRoot: tmpProjectRoot, home: tmpHome,
      });
      expect(result.ok).toBe(true);

      const claude = readFileSync(join(tmpProjectRoot, '.claude', 'CLAUDE.md'), 'utf-8');
      expect(claude).toContain('### CR-99: audit_log_plan_token');
      expect(claude).toContain('rule-candidate abc123def4567890');
      expect(claude).toContain('Every approve must reference a plan token');
    });

    it('conflict-detection: refuses when CR-N already exists in CLAUDE.md', async () => {
      // Pre-seed an existing CR-50 entry
      const claudePath = join(tmpProjectRoot, '.claude', 'CLAUDE.md');
      writeFileSync(claudePath, readFileSync(claudePath, 'utf-8') + '\n### CR-50: pre-existing\n', 'utf-8');
      const id = writeCandidate();
      const result = await applyRuleCandidate(db, {
        candidateId: id, destination: 'claude-md-cr', draftText: 'body',
        slug: 'collision', claudeMdCrNumber: 50,
        projectRoot: tmpProjectRoot, home: tmpHome,
      });
      expect(result.ok).toBe(false);
      expect(result.error).toMatch(/CR-50 entry/);

      // Verify CLAUDE.md was restored (snapshot rollback)
      const claude = readFileSync(claudePath, 'utf-8');
      expect(claude).toContain('### CR-50: pre-existing');
      // Audit_log row rolled back
      const n = (db.prepare(`SELECT COUNT(*) AS n FROM audit_log WHERE event_type='rule_promoted'`).get() as { n: number }).n;
      expect(n).toBe(0);
    });
  });

  describe('custom-destination', () => {
    const customDestination: CustomDestinationConfig = {
      name: 'brand-voice',
      path: 'docs/brand-voice.md',
      triggerKeywords: ['brand voice'],
      template: '## ${date}\n- score: ${score}\n- destination: ${destination_name}\n- preview: ${prompt_preview}\n',
    };

    it('happy path: renders template at the configured path', async () => {
      mkdirSync(join(tmpProjectRoot, 'docs'), { recursive: true });
      writeFileSync(join(tmpProjectRoot, 'docs', 'brand-voice.md'), '# Brand Voice\n', 'utf-8');
      const id = writeCandidate();
      const result = await applyRuleCandidate(db, {
        candidateId: id, destination: 'custom-destination',
        draftText: 'unused for custom-destination — template renders from candidate fields',
        slug: 'brand_voice_tweak', customDestination,
        projectRoot: tmpProjectRoot, home: tmpHome,
      });
      expect(result.ok).toBe(true);

      const dest = readFileSync(join(tmpProjectRoot, 'docs', 'brand-voice.md'), 'utf-8');
      expect(dest).toContain('# Brand Voice');
      expect(dest).toContain('- destination: brand-voice');
      expect(dest).toContain('- score: 90');
      expect(dest).toContain('- preview: use getConfig() instead of direct yaml.load');
    });

    it('rejects paths that escape the project root', async () => {
      const escaping: CustomDestinationConfig = {
        ...customDestination,
        path: '../escape-attempt.md',
      };
      const id = writeCandidate();
      const result = await applyRuleCandidate(db, {
        candidateId: id, destination: 'custom-destination', draftText: 'body',
        slug: 'escape', customDestination: escaping,
        projectRoot: tmpProjectRoot, home: tmpHome,
      });
      expect(result.ok).toBe(false);
      expect(result.error).toMatch(/escapes project root/);
    });

    it('snapshot-set: NEW destination file deleted on rollback', async (ctx) => {
      // No pre-existing dest file → it will be NEW during Step 2.
      const id = writeCandidate();
      const memoryIndex = join(tmpHome, '.claude', 'projects', encodeMemoryDirName(tmpProjectRoot), 'memory', 'MEMORY.md');
      const { chmodSync, statSync } = require('fs');
      chmodSync(memoryIndex, 0o444);
      const writable = (statSync(memoryIndex).mode & 0o200) !== 0;
      // G-1 (plan-2026-07-26-anti-vacuity-9-unproven-gates): chmod is a no-op when running as root, so the Step-3 failure this
      // test needs cannot be forced. ctx.skip() reports SKIPPED; the old `return`
      // reported PASSED for a rollback that was never exercised.
      if (writable) { chmodSync(memoryIndex, 0o644); ctx.skip(); }
      try {
        mkdirSync(join(tmpProjectRoot, 'docs'), { recursive: true });
        const result = await applyRuleCandidate(db, {
          candidateId: id, destination: 'custom-destination', draftText: 'body',
          slug: 'rollback', customDestination,
          projectRoot: tmpProjectRoot, home: tmpHome,
        });
        expect(result.ok).toBe(false);
        // NEW destination file should NOT exist post-rollback
        expect(existsSync(join(tmpProjectRoot, 'docs', 'brand-voice.md'))).toBe(false);
      } finally {
        chmodSync(memoryIndex, 0o644);
      }
    });

    it('rejects custom destination whose template references disallowed var (RCE-guard)', async () => {
      const dangerous: CustomDestinationConfig = {
        ...customDestination,
        template: 'safe prefix ${process.exit(1)} suffix',
      };
      mkdirSync(join(tmpProjectRoot, 'docs'), { recursive: true });
      const id = writeCandidate();
      const result = await applyRuleCandidate(db, {
        candidateId: id, destination: 'custom-destination', draftText: 'body',
        slug: 'rce_attempt', customDestination: dangerous,
        projectRoot: tmpProjectRoot, home: tmpHome,
      });
      expect(result.ok).toBe(false);
      expect(result.error).toMatch(/not in the allowlist|TemplateAllowlistError/);
    });
  });
});
