#!/usr/bin/env bash
# install-hooks — wire git hooks for this clone.
#
# Called automatically by `npm install` via package.json's `postinstall`
# script. Idempotent: re-running is safe and overwrites the hook with
# the latest source-of-truth version.
#
# Why a post-install script: .git/hooks/ is NOT tracked in git (and
# CANNOT be without git's own opt-in via core.hooksPath). Without this
# auto-install, fresh clones have ZERO leak protection until someone
# manually runs install-hooks.sh — which is exactly the failure mode
# that allowed the 2026-04-28→05-06 docs/internal/ leak to ship.
#
# To bypass during local dev (you should not): touch
# .massu-skip-hook-install in the repo root before running npm install.
#
# History: created 2026-05-06 as part of the post-leak enterprise
# defense layering. See the project memory rule
# feedback_public_repo_leak_guard.md for the incident.

set -euo pipefail

# Resolve repo root (handles being called from any working directory,
# including npm's child cwd which is the package being installed).
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
HOOKS_DIR="$REPO_ROOT/.git/hooks"
GUARD_SCRIPT="$REPO_ROOT/scripts/massu-public-leak-guard.sh"

# Skip if .git/ doesn't exist (e.g., this is an extracted tarball,
# not a git clone). The hook only runs in git contexts.
if [ ! -d "$REPO_ROOT/.git" ]; then
  echo "[install-hooks] no .git/ — not a git clone, skipping hook install" >&2
  exit 0
fi

# Skip if user explicitly asked to skip.
if [ -e "$REPO_ROOT/.massu-skip-hook-install" ]; then
  echo "[install-hooks] .massu-skip-hook-install present, skipping" >&2
  exit 0
fi

# Skip if the guard script doesn't exist (older checkout pre-leak-fix).
if [ ! -x "$GUARD_SCRIPT" ]; then
  echo "[install-hooks] $GUARD_SCRIPT missing or non-executable — skipping" >&2
  exit 0
fi

mkdir -p "$HOOKS_DIR"

cat > "$HOOKS_DIR/pre-commit" <<EOF
#!/usr/bin/env bash
# Auto-installed by scripts/install-hooks.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# DO NOT EDIT this file directly — re-run scripts/install-hooks.sh after
# changes to scripts/massu-public-leak-guard.sh.
exec "\$(git rev-parse --show-toplevel)/scripts/massu-public-leak-guard.sh" "\$@"
EOF
chmod +x "$HOOKS_DIR/pre-commit"

# Also install pre-push as a second-chance gate. pre-commit catches
# the moment of authoring; pre-push catches amend / rebase / cherry-pick
# scenarios that introduced new content without a fresh commit.
cat > "$HOOKS_DIR/pre-push" <<EOF
#!/usr/bin/env bash
# Auto-installed by scripts/install-hooks.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# Pre-push gate: re-runs the leak guard against the diff between local
# HEAD and the remote, catching anything that slipped past pre-commit
# (amends, rebases, cherry-picks, --no-verify'd commits).
set -euo pipefail
REPO_ROOT="\$(git rev-parse --show-toplevel)"
GUARD="\$REPO_ROOT/scripts/massu-public-leak-guard.sh"
[ -x "\$GUARD" ] || exit 0

# Inputs from git: each line is "<local_ref> <local_sha> <remote_ref> <remote_sha>"
while read local_ref local_sha remote_ref remote_sha; do
  [ "\$local_sha" = "0000000000000000000000000000000000000000" ] && continue  # branch delete
  if [ "\$remote_sha" = "0000000000000000000000000000000000000000" ]; then
    # New branch — diff against the merge-base with origin/main.
    base=\$(git merge-base "\$local_sha" origin/main 2>/dev/null || echo "")
    range="\${base}..\${local_sha}"
  else
    range="\${remote_sha}..\${local_sha}"
  fi

  # For each commit in the push, stage its diff into a temp index and
  # invoke the guard. We use --diff-filter=ACMR to match what the
  # pre-commit guard already filters.
  for sha in \$(git rev-list --reverse "\$range"); do
    files=\$(git diff-tree --no-commit-id --name-only --diff-filter=ACMR -r "\$sha")
    [ -z "\$files" ] && continue
    # Set up a temp index pointing at this commit so the guard's
    # "git diff --cached" sees the right thing.
    export GIT_INDEX_FILE="\$(mktemp)"
    git read-tree "\$sha"
    if ! "\$GUARD"; then
      rm -f "\$GIT_INDEX_FILE"
      unset GIT_INDEX_FILE
      echo "" >&2
      echo "  pre-push leak guard rejected commit \$sha" >&2
      echo "  Push aborted. Investigate the violations above." >&2
      exit 1
    fi
    rm -f "\$GIT_INDEX_FILE"
    unset GIT_INDEX_FILE
  done
done

exit 0
EOF
chmod +x "$HOOKS_DIR/pre-push"

echo "[install-hooks] installed pre-commit + pre-push at $HOOKS_DIR/" >&2
